### ISSUE TITLE
Please consider to use one and only one values expression, 

### ISSUE THREAD

**Issue by lvhjean** [ClickHouse/clickhouse-java#1106]
WARN [com.clickhouse.jdbc.internal.SqlBasedPreparedStatement.warn:140] - Please consider to use one and only one values expression, for example: use 'values(?)' instead of 'values(?),(?)'.
clickhouse-client:0.3.2-path11
clickhouse-server:21.6.3.14

**Comment by zhicwu** [comment]
Hi @lvhjean, it's a warning so it won't stop you from using PreparedStatement that way. However, I think in general it's better to use single VALUES expression and batch insert instead for better performance. Behind the scene, your way was completed by issue a query string with parameters substituted to ClickHouse, but if you change to batch insert, the driver will send binary data to server for insertion which is usually much faster.

**Comment by lvhjean** [comment]
Thanks, 
I upgraded from an older version (0.3.1-patch).This older version does not have this warning. 
Maybe I rushed the upgrade.
