### ISSUE TITLE
Set delimiter for a INSERT INTO FROM input()

### ISSUE THREAD

**Issue by simper66** [ClickHouse/clickhouse-java#1118]
Hi, 

I am able to insert into a table directly from a java InputStream. Something like:

INSERT INTO my_table SELECT * FROM input(id UInt32, name String) FORMAT CSV

But i don't know how to change the "input" delimiter. I have tried with something like:

```
INSERT INTO my_table
SELECT "name", "male"
SETTINGS
    format_csv_delimiter = ',',
    format_csv_null_representation = 'NULL'
FROM input('"name" String, "male" Bool') 
FORMAT CSV
JHON,T
PETER,T
```
but it seems the keyword "SETTINGS" does not work as in other places.

any ideas?

**Comment by zhicwu** [comment]
Hi @simper66, are you trying to load CSV data into a table? Have you tried something like below?

```sql
set format_csv_delimiter = ',', format_csv_null_representation = 'NULL';
insert into xt(id, stringValue) FORMAT CSV
1,NULL
2,b
```

Behind the scene, JDBC driver will create a session and run the two queries on after the other.
