### ISSUE TITLE
What is the use of 'shaded jar'

### ISSUE THREAD

**Issue by IcebergXTY** [ClickHouse/clickhouse-java#1134]
Hello, I found there are three shaded jar in clickhouse-jdbc, like this
![image](https://user-images.githubusercontent.com/15325243/203710881-68190b1e-9f3f-4ff6-b5ef-d5c9a3364024.png)

The shaded jar brings about some inconvenience —— it can't download sources so I can't see the code comment and the code jump is also invalid. Now it's hard to debug in my application.

In my opinion, shaded jar always used to prevent dependency conflict in other libraries, but they just shaded third party code, their own module code won't be shaded.

So what's the reason you shaded all the code include your own modules?Can it change to just shade the third party code?😁

**Comment by IcebergXTY** [comment]
The shaed jar also has duplicated class like this
![image](https://user-images.githubusercontent.com/15325243/203715572-eaa2456d-a23a-41bb-b033-5c958e47cfc0.png)

I see the document let's us to exclude all the dependencies in <exclusions>, but why not abandon shaded jar like other general maven project?

**Comment by zhicwu** [comment]
Hi @IcebergXTY, thanks for pointing this out. The shaded jars were only used to reduce dependency exclusions when building JDBC driver, which is messy. Will update pom to fix this.

**Comment by zhicwu** [comment]
Re-open as the shaded jar does not contain source for debugging.
