### ISSUE TITLE
is there a compatible bitmap java lib for clickhouse?

### ISSUE THREAD

**Issue by learn2Pro** [ClickHouse/clickhouse-java#1141]
```
<!-- https://mvnrepository.com/artifact/com.clickhouse/org.roaringbitmap -->
<dependency>
    <groupId>com.clickhouse</groupId>
    <artifactId>org.roaringbitmap</artifactId>
    <version>1.5.0</version>
    <scope>provided</scope>
</dependency>
```

is this lib available?

**Comment by zhicwu** [comment]
Hi @learn2Pro, are you using a mirror? You can use maven central to check, for example: https://repo1.maven.org/maven2/com/clickhouse/org.roaringbitmap/1.5.0/.

**Comment by learn2Pro** [comment]
> Hi @learn2Pro, are you using a mirror? You can use maven central to check, for example: https://repo1.maven.org/maven2/com/clickhouse/org.roaringbitmap/1.5.0/.

i try but not work with this lib, the 64bitmap result still incorrect

**Comment by learn2Pro** [comment]
should i contribute for this?

**Comment by zhicwu** [comment]
Finally... But the change has not released yet.

Of course you can contribute. Please use develop branch and add more tests in the pull request.

A few more things you may want to consider:
* implement ClickHouseDeserializer and ClickHouseSerializer interfaces
* Use input/output stream instead ByteBuffer
* extract ClickHouse compatible bitmap implementation and remove RoaringBitmap dedependency - avoid unnecessary byte array copying
