### ISSUE TITLE
USE statement does nothing

### ISSUE THREAD

**Issue by kassak** [ClickHouse/clickhouse-java#1160]
```
driver version: 0.3.2-patch11
ClickHouse: 21.12.4.1
```

New implementation of driver does not change the schema stored inside the connection, so the statements after USE are executed in schema that was originally configured in the settings

Example:
```
use system;
select currentDatabase();
use default;
select currentDatabase();
```

**Comment by zhicwu** [comment]
Hi @kassak, thanks for the report. I can reproduce the issue.

**Comment by tjlee** [comment]
@zhicwu I can reproduce the issue too. Maybe we missed something in steps to reproduce, do you need any help?

In image you can see that driver returns invalid value for `currentDatabase()` after `use` statements
<img width="828" alt="In image you can see that driver returns invalid value for current database" src="https://user-images.githubusercontent.com/1133087/211608162-ef614233-62af-42a3-a1b1-24f2f5bfe3cc.png">

**Comment by zhicwu** [comment]
Thank you @tjlee for additional inputs. I plan to fix this together with TCL support to close #975.

Yes I do need help :) Are we expecting to change schema at Connection level? There are two typical scenarios:
1. issue `USE <db>` - should be same as calling `Connection.setSchema()`
2. issue multi-statement query which contains `USE` statement - similar as above

Actually I thought about applying the change at Statement level especially for the second one, but it's probably inconsistent with other database drivers. Any suggestion?

**Comment by kassak** [comment]
>  inconsistent with other database drivers

Yes that would be inconsistent and unexpected, especially for interactive tools)
From my experience I can say:
The current schema is usually not applied while sending the statement to db, and maintained solely by the database.
Some drivers do cache it from the database responses.

**Comment by yanye666** [comment]
ClickHouse does not support catalog, please use setSchema instead

**Comment by zhicwu** [comment]
Sorry for getting back late. Now the driver supports both catalog and schema(change `databaseTerm` option to switch) and each time you change current database(either catalog or schema, depending databaseTerm option), the driver will check existence of the database.

I don't have DataGrip license, so I only verified the change on DBeaver. Appreciate if you can use latest nightly build at [here](https://s01.oss.sonatype.org/content/repositories/snapshots/com/clickhouse/clickhouse-jdbc/0.4.2-SNAPSHOT/) to double check.
