### ISSUE TITLE
A bug occurs when jdbc writes to array (byte)

### ISSUE THREAD

**Issue by Sivannnnnn** [ClickHouse/clickhouse-java#1173]
I can successfully write binary data to clickhouse using statement.setBytes through jdbc when the clickhouse field type is string.
But now I have a string of type array that fails to be written when I use the method statement.setArray(1, conn.createArrayOf("Array(Byte)", photosF)). The value written to the clickhouse array is the java array address, such as ['[B@4044e2d6'].
I get the same result using statement.setArray(1, conn.createArrayOf("String", photosF)), photosF is a two-dimensional array, byte[][]

**Comment by zhicwu** [comment]
Hi @Sivannnnnn, what's the query for insertion? Please avoid to use `Connection.createArrayOf` as it's slow and involving unnecessary object creation, you may use `PreparedStatement.setObject` and pass an array instead.

**Comment by Sivannnnnn** [comment]
@zhicwu hello,
My goal is to store binaries in clickhouse. I can successfully write by statement.setBytes(1,byte[]) when it is not an array type binary string, but now it is an array type binary, Using your method statement.setObject(1,byte[][]),clickhouse writes the java object address ['[B@4044e2d6'] instead of the binary data, as shown in the figure
![image](https://user-images.githubusercontent.com/46392469/210676655-07c599f7-0896-4bef-a014-d2e70ad037c9.png)

**Comment by Sivannnnnn** [comment]
is there anyone?

**Comment by Sivannnnnn** [comment]
this is my table,
![image](https://user-images.githubusercontent.com/46392469/210725013-32b5900f-7b55-4a00-92d2-56ce3b0c2201.png)

**Comment by zhicwu** [comment]
Sorry for the late response. Can you provide the query and sample code for insertion? My guess is the parameter was converted to string due to lack of type information. You may want to check [batch insert example](https://github.com/ClickHouse/clickhouse-jdbc/blob/f61c90327a1cfe60ec01027fd6e3dc5a497ca5af/examples/jdbc/src/main/java/com/clickhouse/examples/jdbc/Basic.java#L89).

**Comment by Sivannnnnn** [comment]
table:
CREATE TABLE test
(
    `id_number` String,
    `feature` String,
    `photos.f` Array(String)
)
ENGINE = MergeTree()
ORDER BY (id_number)
SETTINGS index_granularity = 8192


pom:
<dependency>
    
    <groupId>com.clickhouse</groupId>
    <artifactId>clickhouse-jdbc</artifactId>
    <version>0.3.2-patch11</version>
    
    <classifier>all</classifier>
    <exclusions>
        <exclusion>
            <groupId>*</groupId>
            <artifactId>*</artifactId>
        </exclusion>
    </exclusions>
</dependency>

java code:
String idNumber = "xxx";
String feature = "Iyj0tEm2VrJyssi16LQVtAw5UjSgsr82DTJctzgcf7hxuB6xd7aetLssubdasN8tc6PlNa80pjWANnoyqawepQoyBzbHsYy0e7FvNioucTOUN463iCkutVKu/6hkMTc2rTBONjE1JTQRKOy1prZqLx+3CjOPMNe3+bYbuJQ1XayUMoE0mLIAMUszrjB2sLAwdK5wMTuyHrA3t2YrYDCuNfUsCrUwsDk05yw8uJSnjjQft440pTTGNu8y67PyMyA3Tq0INsS02bElt2Qut7NmmhCwbSzfn6U45zfpsaatnrP/NY0yhrXBLAE2USILNkW4HbWdpXm0kjW9mKA4Cq9vLQ==";
byte[][] photosF = new byte[2][];
byte[] featureArray = Base64.getDecoder().decode(feature);
photosF[0] = featureArray;
photosF[1] = featureArray;
String insertSql = "insert into test(id_number,feature,photos.f) values(?,?,?)";
preparedstatement.setString(1,idNumber);
preparedstatement.setBytes(2,featureArray);
preparedstatement.setObject(3,photosF);



result:
SELECT
    id_number,
    base64Encode(feature),
    base64Encode(arrayJoin(photos.f))
FROM test;

name: xxx
feature: Iyj0tEm2VrJyssi16LQVtAw5UjSgsr82DTJctzgcf7hxuB6xd7aetLssubdasN8tc6PlNa80pjWANnoyqawepQoyBzbHsYy0e7FvNioucTOUN463iCkutVKu/6hkMTc2rTBONjE1JTQRKOy1prZqLx+3CjOPMNe3+bYbuJQ1XayUMoE0mLIAMUszrjB2sLAwdK5wMTuyHrA3t2YrYDCuNfUsCrUwsDk05yw8uJSnjjQft440pTTGNu8y67PyMyA3Tq0INsS02bElt2Qut7NmmhCwbSzfn6U45zfpsaatnrP/NY0yhrXBLAE2USILNkW4HbWdpXm0kjW9mKA4Cq9vLQ==
base64Encode(arrayJoin(photos.f)): W0JAYjg0MjEyYQ==
base64Encode(arrayJoin(photos.f)): W0JANTY1ZjRjNTM=

my expect data is :
name: xxx
feature: Iyj0tEm2VrJyssi16LQVtAw5UjSgsr82DTJctzgcf7hxuB6xd7aetLssubdasN8tc6PlNa80pjWANnoyqawepQoyBzbHsYy0e7FvNioucTOUN463iCkutVKu/6hkMTc2rTBONjE1JTQRKOy1prZqLx+3CjOPMNe3+bYbuJQ1XayUMoE0mLIAMUszrjB2sLAwdK5wMTuyHrA3t2YrYDCuNfUsCrUwsDk05yw8uJSnjjQft440pTTGNu8y67PyMyA3Tq0INsS02bElt2Qut7NmmhCwbSzfn6U45zfpsaatnrP/NY0yhrXBLAE2USILNkW4HbWdpXm0kjW9mKA4Cq9vLQ==
base64Encode(arrayJoin(photos.f)): Iyj0tEm2VrJyssi16LQVtAw5UjSgsr82DTJctzgcf7hxuB6xd7aetLssubdasN8tc6PlNa80pjWANnoyqawepQoyBzbHsYy0e7FvNioucTOUN463iCkutVKu/6hkMTc2rTBONjE1JTQRKOy1prZqLx+3CjOPMNe3+bYbuJQ1XayUMoE0mLIAMUszrjB2sLAwdK5wMTuyHrA3t2YrYDCuNfUsCrUwsDk05yw8uJSnjjQft440pTTGNu8y67PyMyA3Tq0INsS02bElt2Qut7NmmhCwbSzfn6U45zfpsaatnrP/NY0yhrXBLAE2USILNkW4HbWdpXm0kjW9mKA4Cq9vLQ==
base64Encode(arrayJoin(photos.f)): Iyj0tEm2VrJyssi16LQVtAw5UjSgsr82DTJctzgcf7hxuB6xd7aetLssubdasN8tc6PlNa80pjWANnoyqawepQoyBzbHsYy0e7FvNioucTOUN463iCkutVKu/6hkMTc2rTBONjE1JTQRKOy1prZqLx+3CjOPMNe3+bYbuJQ1XayUMoE0mLIAMUszrjB2sLAwdK5wMTuyHrA3t2YrYDCuNfUsCrUwsDk05yw8uJSnjjQft440pTTGNu8y67PyMyA3Tq0INsS02bElt2Qut7NmmhCwbSzfn6U45zfpsaatnrP/NY0yhrXBLAE2USILNkW4HbWdpXm0kjW9mKA4Cq9vLQ==

**Comment by Sivannnnnn** [comment]
@zhicwu 
hello ,this is the query and sample code for insertion

**Comment by zhicwu** [comment]
> @zhicwu hello ,this is the query and sample code for insertion

Thanks for the details. Will try it when I get home.

**Comment by Sivannnnnn** [comment]
ok, thank you, when i use ru.yandex.clickhouse ,clickhouse-jdbc-0.2 , i can insert data sucessful . but use this driver , i get failed

**Comment by Sivannnnnn** [comment]
> 

ok, thank you, when i use ru.yandex.clickhouse ,clickhouse-jdbc-0.2 , i can insert data sucessful . but use this driver , i get failed

**Comment by zhicwu** [comment]
If you want `byte[]` in ClickHouse, you may use `Array(Int8)` (`Array(UInt8)` is mapped to `short[]`) and similarly `Array(Array(Int8))` for `byte[][]` in Java. Below code works in 0.3.2-patch11 and 0.4:
```java
try (Statement s = conn.createStatement()) {
    s.execute("drop table if exists test_insert_byte_array;"
            + "create table test_insert_byte_array(id String, b Array(Int8), s Array(Array(Int8))) engine=Memory");
    try (PreparedStatement stmt = conn.prepareStatement(
            "insert into test_insert_byte_array(id, b, s) values (?,?,?)")) {
        stmt.setString(1, "1");
        stmt.setObject(2, new byte[] { 1, 2, 3 });
        stmt.setObject(3, new byte[][] { { 1, 2, 3 }, { 4, 5, 6 } });
        stmt.execute();

        try (ResultSet rs = s.executeQuery("select * from test_insert_byte_array order by id")) {
            System.out.println(rs.next());
            System.out.println(rs.getInt(1));
            System.out.println(rs.getObject(2));
            System.out.println(rs.getObject(3));
        }
    }
}
```

Starting from 0.4(try nightly build), `use_binary_string` is required for binary string support(mainly due to performance reason), and `Array(UInt8)` is mapped to `byte[]` by default.
```java
Properties props = new Properties();
props.setProperty("use_binary_string", "true");
try (ClickHouseConnection conn = newConnection(props); Statement s = conn.createStatement()) {
    s.execute("drop table if exists test_insert_byte_array;"
            + "create table test_insert_byte_array(id String, b Array(UInt8), s Array(String)) engine=Memory");
    try (PreparedStatement stmt = conn.prepareStatement(
            "insert into test_insert_byte_array(id, b, s) values (?,?,?)")) {
        stmt.setString(1, "1");
        stmt.setBytes(2, new byte[] { 1, 2, 3 });
        stmt.setObject(3, new byte[][] { { 1, 2, 3 }, { 4, 5, 6 } });
        Assert.assertEquals(stmt.executeUpdate(), 1);

        ResultSet rs = s.executeQuery("select * from test_insert_byte_array order by id");
        Assert.assertTrue(rs.next());
        Assert.assertEquals(rs.getInt(1), 1);
        Assert.assertEquals(rs.getObject(2), new byte[] { 1, 2, 3 });
        Assert.assertEquals(rs.getObject(3), new byte[][] { { 1, 2, 3 }, { 4, 5, 6 } });
        Assert.assertFalse(rs.next());
    }
}
```
