### ISSUE TITLE
HikariCP timeout with com.clickhouse.jdbc.ClickHouseDataSource

### ISSUE THREAD

**Issue by wzisheng** [ClickHouse/clickhouse-java#1214]
clickhouse-jdbc 0.3.2 with HikariCP 4.0.3

if we use `com.clickhouse.jdbc.ClickHouseDataSource`, and convert to HikariCP datasource, then we got 
![image](https://user-images.githubusercontent.com/87692633/215655164-b1aa3b1f-d5e9-427c-83e7-c9f01c5fa743.png)

while `ru.yandex.clickhouse.clickhousedatasource` works fine.
BTW, we use https

**Comment by zhicwu** [comment]
Hi @wzisheng, I didn't see JDBC driver show up in above stack trace. Could you elaborate? Would be great if you can provide minimal code for reproducing the issue.

**Comment by wzisheng** [comment]
private static DataSource convertToHikari(final DataSource dataSource) {
    HikariConfig hikariConfig = new HikariConfig();
    hikariConfig.setConnectionTimeout(10000);
    hikariConfig.setMaximumPoolSize(20);
    hikariConfig.setMinimumIdle(18000);
    hikariConfig.setMaxLifetime(10000);
    hikariConfig.setDataSource(dataSource);
    return new HikariDataSource(hikariConfig);
}


properties.put("ssl", "true");
properties.put("sslmode", "NONE");
DataSource dataSource = convertToHikari(new ClickHouseDataSource(url, properties));
try (Connection connection = dastaSource.getConnection();
    Statement statement = connection.createStatement();
    ResultSet result = statement.executeQuery(sql)) {
    int count = 0;
    if (result.next()) {
        count = result.getInt("aa");
    }
    System.out.println(count);
} catch (Exception e) {
    e.printStackTrace();
}

**Comment by zhicwu** [comment]
Not able to reproduce. Please make sure the url is valid and server is reachable from client.

Anyway, I updated examples by adding [usePooledConnection()](https://github.com/ClickHouse/clickhouse-java/blob/03e42c5f0574e819381628ea978c5928528c02d4/examples/jdbc/src/main/java/com/clickhouse/examples/jdbc/Basic.java#L213-L231) which works well.

**Comment by wzisheng** [comment]
> Not able to reproduce. Please make sure the url is valid and server is reachable from client.
> 
> Anyway, I updated examples by adding [usePooledConnection()](https://github.com/ClickHouse/clickhouse-java/blob/03e42c5f0574e819381628ea978c5928528c02d4/examples/jdbc/src/main/java/com/clickhouse/examples/jdbc/Basic.java#L213-L231) which works well.

seems [usePooledConnection()](https://github.com/ClickHouse/clickhouse-java/blob/03e42c5f0574e819381628ea978c5928528c02d4/examples/jdbc/src/main/java/com/clickhouse/examples/jdbc/Basic.java#L213-L231) only use executes once, which in mine the first time it works fine .  Only if the 2nd or 3/4th time it will produce..
@zhicwu

**Comment by zhicwu** [comment]
> Only if the 2nd or 3/4th time it will produce..

Tried a loop for 1000 times(pool size=20) and still not able to reproduce. Please feel free to reopen the issue if you're certain it's caused by the driver.
