### ISSUE TITLE
Nested arrays seem to be broken in 0.4.0

### ISSUE THREAD

**Issue by slvrtrn** [ClickHouse/clickhouse-java#1221]
Minimal reproducible scenario:

```java
package ch;

import com.clickhouse.jdbc.ClickHouseDataSource;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Arrays;
import java.util.Properties;

public class ArrayTest {
    public static void main(String[] args) {
        String url = "jdbc:ch:http://localhost:8123/default";
        Properties properties = new Properties();
        properties.setProperty("user", "default");
        properties.setProperty("password", "");
        try {
            ClickHouseDataSource ds = new ClickHouseDataSource(url, properties);
            Connection conn = ds.getConnection();
            Statement stmt = conn.createStatement();
            stmt.executeQuery("drop table if exists test_data_array_of_arrays");
            stmt.executeQuery("""
                      create table test_data_array_of_arrays
                      (id Int32, my_array_of_arrays Array(Array(String)))
                      engine MergeTree order by id
                    """);
            stmt.execute("""
                    insert into test_data_array_of_arrays values
                    (1, [['foo', 'bar'], ['qaz', 'qux']]),
                    (2, []);
                    """);
            ResultSet rs = stmt.executeQuery("select * from test_data_array_of_arrays");
            while (rs.next()) {
                Arrays.stream(((String[][]) rs.getArray(2).getArray())).toList().forEach((innerArray) -> {
                    System.out.println(Arrays.toString(innerArray));
                });
            }
            System.exit(0);
        } catch (Exception e) {
            Common.logException(e);
            System.exit(1);
        }

    }
}
```

0.3.2-patch11 correctly prints:

```
[foo, bar]
[qaz, qux]
```

0.4.0 incorrectly prints:

```
[qaz, qux]
[qaz, qux]
```

Found this purely by accident cause I have a weird "Arrays of Arrays" test in the Metabase plugin, and all of a sudden [this method](https://github.com/ClickHouse/metabase-clickhouse-driver/blob/master/src/metabase/driver/clickhouse.clj#L447-L460) started to produce incorrect results after the upgrade to 0.4.0 (see the [JUnit report](https://github.com/ClickHouse/metabase-clickhouse-driver/actions/runs/4076119078/jobs/7023741553))

Is it indeed something wrong with the ResultSet as of 0.4.0, or am I doing it incorrectly in the code?

**Comment by zhicwu** [comment]
Thanks for reporting the issue. It's caused below code(and similarly in all ArrayValue classes), which intents to save memory 😓 Removing the check will fix the issue but it will result in poor performance and high memory usage. Let me think this  through and come up with a PR along with more tests later today.

https://github.com/ClickHouse/clickhouse-java/blob/03e42c5f0574e819381628ea978c5928528c02d4/clickhouse-data/src/main/java/com/clickhouse/data/value/ClickHouseArrayValue.java#L561-L575
