### ISSUE TITLE
how to upload external table with jdbc 0.3.2-patch11

### ISSUE THREAD

**Issue by chigend** [ClickHouse/clickhouse-java#1231]
i want to implment external data query procecessing reference by clickhouse doc https://clickhouse.com/docs/en/engines/table-engines/special/external-data/

but i want to implement this in jdbc

i can find old version implementation for package "ru.yandex.clickhouse.ClickHouseDataSource", here is the solution

https://github.com/ClickHouse/ClickHouse/issues/17219

but now package "ru.yandex.clickhouse" has been replaced by "com.clickhouse.jdbc", and some implementation has changed,

so what's the package "com.clickhouse.jdbc" version to upload external table

**Comment by chigend** [comment]
@zhicwu

**Comment by zhicwu** [comment]
Hi @chigend, you may search `external` in the repository to find examples and tests to start with. For instance, https://github.com/ClickHouse/clickhouse-java/blob/c676f8c363ece6cee04fbbfbe3dbd7d0ea0842e0/examples/jdbc/src/main/java/com/clickhouse/examples/jdbc/Advanced.java#L63-L83.

**Comment by chigend** [comment]
what if we have other non-external-table parameter

**Comment by yanye666** [comment]
> 如果我们有其他非外部表参数怎么办@zhicwu
It looks like the sql for the external table has to be written dead, there is no support for compatibility with precompiled and external tables

Can you try intercepting sql to handle yourself in precompile?

**Comment by hantaoliulinux** [comment]
Hello, I would like to ask, the code to switch from ru.yandex to com.clickhouse with jdbc 0.3.2-patch11 , like this ssl, socketTimeout set, after the switch should how to set?

ClickHouseProperties clickHouseProperties = new ClickHouseProperties();
clickHouseProperties.setSocketTimeout(60000);
clickHouseProperties.setSsl(true);
clickHouseProperties.setSslMode("none");

**Comment by yanye666** [comment]
> 

try

`
Properties props = new Properties();

        props.setProperty(ClickHouseClientOption.SSL.getKey(),true);
`



> 你好，请问，从ru.yandex 切换到com.clickhouse 的代码是用jdbc 0.3.2-patch11 ，像这样ssl，socketTimeout 设置，切换之后应该怎么设置？
> 
> ClickHouseProperties clickHouseProperties = new ClickHouseProperties(); 点击HouseProperties.setSocketTimeout(60000); 点击HouseProperties.setSsl(true); 点击HouseProperties.setSslMode("无");

> 

try

`
Properties props = new Properties();
props.setProperty(ClickHouseClientOption.SSL.getKey(),true);
`

**Comment by hantaoliulinux** [comment]
thanks



---Original---
From: ***@***.***&gt;
Date: Tue, Mar 14, 2023 14:34 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ClickHouse/clickhouse-java] how to upload external table withjdbc 0.3.2-patch11 (Issue #1231)




   
try
 
`
 Properties props = new Properties();
     props.setProperty(ClickHouseClientOption.SSL.getKey(),true);  
`
  
你好，请问，从ru.yandex 切换到com.clickhouse 的代码是用jdbc 0.3.2-patch11 ，像这样ssl，socketTimeout 设置，切换之后应该怎么设置？
 
ClickHouseProperties clickHouseProperties = new ClickHouseProperties(); 点击HouseProperties.setSocketTimeout(60000); 点击HouseProperties.setSsl(true); 点击HouseProperties.setSslMode("无");
    
try
 
Properties props = new Properties(); props.setProperty(ClickHouseClientOption.SSL.getKey(),true);

**Comment by zhicwu** [comment]
You may also check out [this](https://github.com/ClickHouse/clickhouse-java/tree/main/clickhouse-jdbc#upgrade-path) for upgrading.

**Comment by hantaoliulinux** [comment]
https://github.com/ClickHouse/clickhouse-java/issues/1231#issuecomment-1467447210

Hello, I would like to ask another question, when I set the transaction to manually commit, directly connect to clickhouse, is normal; However, if I want to access clickhouse through the Nginx load balancing, an error message is displayed, indicating "Invalid transaction due to session not found or timeed out". I feel that the reverse proxy lost the session. I am trying to solve the problem. I don't know if I have any experience.
