### ISSUE TITLE
batchUpdateError: infinite recursion

### ISSUE THREAD

**Issue by pavel-kolesov** [ClickHouse/clickhouse-java#1233]
https://github.com/ClickHouse/clickhouse-java/blob/bf885a9eebd2a905a5cc0e4d3272ea3b43062c67/clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/SqlExceptionUtils.java#L106

**Comment by zhicwu** [comment]
Thanks @pavel-kolesov! This is really stupid, let me fix it now.
