### ISSUE TITLE
How to get live view result

### ISSUE THREAD

**Issue by VanKuang** [ClickHouse/clickhouse-java#1239]
Hi,

I tried both jdbc and http client to execute a query "watch xxx_view", but both of then got timeout exception eventually.
May I know does clickhouse-java support watch live view? if yes, how?

Thanks,
Van

**Comment by zhicwu** [comment]
Hi @VanKuang, sorry it's not supported. The timeout is due to current implementation, which expects everything returned from server within reasonable timeout but apparently not the case for live view.

**Comment by VanKuang** [comment]
您好！我已经收到您发的邮件了。

**Comment by mzitnik** [comment]
@zhicwu Can you open an issue with detail explanation for what we need to support here

**Comment by VanKuang** [comment]
您好！我已经收到您发的邮件了。

**Comment by alexey-milovidov** [comment]
Live views are not supported by ClickHouse.

**Comment by zhicwu** [comment]
> Live views are not supported by ClickHouse.

It's still an experimental feature at least in 23.7. Is it going to be dropped in the near future?

**Comment by alexey-milovidov** [comment]
It's unclear; maybe they will be dropped. Currently no guarantees.
