### ISSUE TITLE
java.lang.NoSuchFieldError: Companion. When my project reference okhttp3.

### ISSUE THREAD

**Issue by xywendz** [ClickHouse/clickhouse-java#1241]
![youdu图片20230215121857](https://user-images.githubusercontent.com/3920956/218929073-5f3f95bd-f526-4bd2-9b25-2a7ef67b8550.png)

My project refeenced okhttp3, version 4.7.2. Keep reporting errors when using clickhouse-jdbc, "java.lang.NoSuchFieldError: Companion" 。During the inspection, the io.rpc.jar package of clickhouse was found and the okio code was packaged, which led to version compatibility problems. 

Solution method，exclude grpc and io.grpc package.
```    
    <dependency>
            <groupId>com.clickhouse</groupId>
            <artifactId>clickhouse-jdbc</artifactId>
            <version>0.4.0</version>
            <classifier>http</classifier>
            <exclusions>
                <exclusion>
                    <groupId>com.clickhouse</groupId>
                    <artifactId>io.grpc</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.clickhouse</groupId>
                    <artifactId>clickhouse-grpc-client</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

**Comment by zhicwu** [comment]
Sorry for the inconvenience @xywendz. I'll make all dependencies in `clickhouse-jdbc` optional, so that nobody has to do this ever again.
