### ISSUE TITLE
Schema listing fetch is extremely slow

### ISSUE THREAD

**Issue by shabalin** [ClickHouse/clickhouse-java#1245]
Hi!
We are facing an issue with fetching schemas metadata, the request takes more than 30 seconds, bringing back about 10 records, not so close to Clickhouse performance standards.

ClickHouseDatabaseMetaData.getSchemas basically does two things:

1. `select name as TABLE_SCHEM, null as TABLE_CATALOG  from system.databases order by name` -  takes few milliseconds
2. `select * from jdbc('', 'SHOW DATASOURCES')`  - takes 30 seconds.
    console output:
    ```
    default> select * from jdbc('', 'SHOW DATASOURCES')
   [2023-02-16 10:40:18] 1 row retrieved starting from 1 in 31 s 882 ms (execution: 31 s 834 ms, fetching: 48 ms)
    ```
    results:
    ```
    script,0,1816107175,2023-02-09 12:37:15,general,"{""id"":""script"",""driverUrls"":[""/d/Tools/groovy-3.0.7/lib"",""!/d/Tools/groovy-3.0.7/lib/groovy-jaxb-3.0.7.jar"",""D:/Tools/groovy-3.0.7/lib"",""!D:/Tools/groovy-3.0.7/lib/groovy-jaxb-3.0.7.jar""],""sealed"":false,""parameters"":{""batch_size"":""100"",""custom_columns"":""false"",""datasource_column"":""false"",""debug"":""false"",""fetch_size"":""1000"",""max_rows"":""0"",""mutation"":""false"",""no_cache"":""false"",""null_as_default"":""false"",""offset"":""0"",""position"":""0"",""timeout"":""-1""}}","{""Bool"":""0"",""Date"":""1"",""DateTime"":""1"",""DateTime64"":""1000"",""Decimal"":""0"",""Decimal128"":""0"",""Decimal256"":""0"",""Decimal32"":""0"",""Decimal64"":""0"",""Enum"":""0"",""Enum16"":""0"",""Enum8"":""0"",""FixedStr"":"""",""Float32"":""0.0"",""Float64"":""0.0"",""IPv4"":""0"",""IPv6"":"""",""Int128"":""0"",""Int16"":""0"",""Int256"":""0"",""Int32"":""0"",""Int64"":""0"",""Int8"":""0"",""Str"":"""",""UInt128"":""0"",""UInt16"":""0"",""UInt256"":""0"",""UInt32"":""0"",""UInt64"":""0"",""UInt8"":""0"",""UUID"":""00000000-0000-0000-0000-000000000000""}",[],"{""hitCount"":0,""missCount"":0,""loadSuccessCount"":0,""loadFailureCount"":0,""totalLoadTime"":0,""evictionCount"":0,""evictionWeight"":0}",{}
    ```
    

and then those two result sets get merged...  

https://github.com/ClickHouse/clickhouse-java/blob/main/clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/ClickHouseDatabaseMetaData.java#L1211

Server version: 22.6.1.1802
Driver version: 0.4.0

1. Would you guys give us any hints why the second part can be so slow? 
2. I think you should somehow make the second call optional, would you agree?

**Comment by zhicwu** [comment]
Hi @shabalin, thanks for reporting the issue.

> not so close to Clickhouse performance standards.

Haha, true :D


> 1. Would you guys give us any hints why the second part can be so slow?

It's for retrieving list of external datasources from JDBC bridge. It's a few seconds(still slow) returning ~50 datasources world-wide in my case. Perhaps there's connection issue between the ClickHouse server and JDBC bridge, since there's only one datasource `script`. If JDBC bridge is not in-use, you probably should shut it down and/or change configuration in ClickHouse accordingly. Also 30-ish seconds sounds like timeout (on JDBC bridge side?).

> 2. I think you should somehow make the second call optional, would you agree?

Yes, will add an option in JDBC driver to turn it off but leave it on by default for backward compatibility.
