### ISSUE TITLE
Passing settings when executing CSV bulk load

### ISSUE THREAD

**Issue by obeah** [ClickHouse/clickhouse-java#1258]
Hi, 

after upgrading to 0.4.1 as per instructions in another issue (#1001) I try the following code to bulk load csv:
```
st.unwrap(ClickHouseRequest.class)
	.write()
	.data(ClickHouseFile.of(new File(csvPath)))
	.table("table1")
	.format(ClickHouseFormat.CSVWithNames)
	.executeAndWait();
```
and it works
But I also need to pass some setting. After I add thew following to the chain:
```
.settings(ImmutableMap.of(
	"format_csv_delimiter", csvSeparator.toString(),
	"date_time_input_format", "best_effort"
	))
```
I get an exception:
Caused by: com.clickhouse.client.ClickHouseException: Expect one SQL statement to execute but we got 3, server ClickHouseNode

Before upgrading I used .option("date_time_input_format", "best_effort")

What would be the correct way of passing settings in this version?

**Comment by zhicwu** [comment]
Hi @obeah, thanks for the report. I think it's same as #1246. Since options/custom settings did not work, perhaps you can try to use custom query? For example:
```java
.write()
	.data(ClickHouseFile.of(new File(csvPath)))
	.query("insert into table1 settings a=1,b=2 format CSV")
	.format(ClickHouseFormat.CSVWithNames)
	.executeAndWait();
```

**Comment by obeah** [comment]
Hi @zhicwu ,

thank you. Yes, it seems like duplicate. Will close it.
And you suggestion solves it for me. Final version
```
write()
.data(ClickHouseFile.of(new File(csvPath)))
.query(String.format("insert into %s settings %s='%s', %s='%s' format CSVWithNames", 
	"table1", "format_csv_delimiter", pCsvSeparator.toString(),
	"date_time_input_format", "best_effort"))
.executeAndWait();
```
