### ISSUE TITLE
ClickHouseDefaultSslContextProvider contains a mistake fetching algorithm from PEM

### ISSUE THREAD

**Issue by catahoc** [ClickHouse/clickhouse-java#1274]
### Steps to reproduce
1. generate key in PEM starting with "-----BEGIN RSA PRIVATE KEY-----"
2. use it in ClickHouseDataSource
3. try to query database
4. NoSuchAlgorithmException " RSA KeyFactory not available"

ClickHouseDefaultSslContextProvider  fetches algorithm name as " RSA" instead of "RSA". Either algorithm needs to be fixed, or trimming added

**Comment by zhicwu** [comment]
Thanks for reporting the issue @catahoc! No idea why I added `- 1` there...

**Comment by catahoc** [comment]
Thanks for fix @zhicwu !
I have a question - shouldn't it possible to use user-provided SSLContext? IMO clickhouse does pretty low-level SSL-related computations there in ClickhouseClient, that can easily have many more issues, because SSL world is extremely complex

**Comment by zhicwu** [comment]
Sorry for the late reply. Currently we can only implement `ClickHouseSslContextProvider` to customize. For instance, extending `ClickHouseDefaultSslContextProvider` by overriding `getJavaSslContext` method. Any suggestion?
