### ISSUE TITLE
How to connect to clickhouse cluster through clickhouse-http-client?

### ISSUE THREAD

**Issue by zhyan099** [ClickHouse/clickhouse-java#1295]
I want to use ‘clickhouse.endpoint=http://ip1:8123,http://ip2:8123,http://ip3:8123’ connect to clickhouse cluster through clickhouse-http-client，How do I need to set up？clickhouse-http-client version is 0.3.2-patch11.
If not, which method do I need to use to solve the problem?

**Comment by zhicwu** [comment]
Hi @zhyan099, ClickHouseClient can connect to a single node represented by `ClickHouseNode` or list of nodes like `ClickHouseNodes.of("http://host1,host2,host3/bb?database=cc&socket_timeout=12345&failover=7&load_balancing_policy=roundRobin")` port number was omitted because by default it's 8123 for http.

https://github.com/ClickHouse/clickhouse-java/blob/90fc6b6f747255efb68441744d250bf9668d4087/clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseClient.java#L992-L994

**Comment by GerryYuan** [comment]
Have you encountered the following problems? When using the http protocol to connect to ck, the following errors occur.
```java
public static void main(String[] args) throws ExecutionException, InterruptedException {
        final ClickHouseNode node = ClickHouseNode.of("localhost", ClickHouseProtocol.HTTP, 8123, "default");
        final ClickHouseResponse response = ClickHouseClient.newInstance(node.getProtocol()).read(node)
            .format(ClickHouseFormat.RowBinaryWithNamesAndTypes)
            .query("SELECT version()").execute().get();
        System.out.println(response.stream().count());
    }
```
```java
java.util.concurrent.ExecutionException: java.net.ConnectException: No client available
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at org.watchinsight.storage.clickhouse.service.ClickHouseService.main(ClickHouseService.java:73)
Caused by: java.net.ConnectException: No client available
	at com.clickhouse.client.ClickHouseClientBuilder$DummyClient.execute(ClickHouseClientBuilder.java:56)
	at com.clickhouse.client.ClickHouseClientBuilder$Agent.execute(ClickHouseClientBuilder.java:346)
	at com.clickhouse.client.ClickHouseRequest.execute(ClickHouseRequest.java:2144)
	... 1 more

```
```maven
<dependency>
      <groupId>com.clickhouse</groupId>
      <artifactId>clickhouse-grpc-client</artifactId>
      <version>0.4.2</version>
</dependency>
```
![image](https://user-images.githubusercontent.com/11907624/227786819-29651ccd-8f9b-41be-b5ab-7747060d283f.png)

DBMS: ClickHouse (ver. 23.2.4.12)
Case sensitivity: plain=exact, delimited=exact
Driver: ClickHouse JDBC Driver (ver. 0.4.0 (revision: https://github.com/ClickHouse/clickhouse-java/commit/3a53cf125350562b438d48f515e265e00b8e962e), JDBC4.2)
