### ISSUE TITLE
Pyspark: Implicit transaction option breaks HTTPDriver

### ISSUE THREAD

**Issue by mwitteveen** [ClickHouse/clickhouse-java#1302]
### Describe the bug

when I set the implicit_transaction option to 1 on a user level through ALTER USER default SETTINGS implicit_transaction=1;

I get the following error:

clickhouse_connect.driver.exceptions.DatabaseError: :HTTPDriver for <URL> returned response code 501)
 Code: 48. DB::Exception: Transactions are not supported: while starting a transaction with 'implicit_transaction'. (NOT_IMPLEMENTED) (version 22.13.1.24479 (official build))

### Steps to reproduce
see above

### Expected behaviour
not to affect the driver

#### Environment
* Client version: 0.4.2-all

**Comment by zhicwu** [comment]
Hi @mwitteveen, it does not look like a bug in the JDBC driver, since it's an error returned from the server.

Did you enable transaction support in ClickHouse? It's an experimental feature requiring ZooKeeper or ClickHouse Keeper, although it only supports local tables.
