### ISSUE TITLE
java.lang.RuntimeException: Parse exception: ByteFragment

### ISSUE THREAD

**Issue by TimonKK** [ClickHouse/clickhouse-java#131]
I have query

SELECT 
    date, 
    groupArray([widget, toString(actionCount)]) AS widgetList
FROM 
(
    SELECT 
        date, 
        arrayJoin(queries) AS widget, 
        count(*) AS actionCount
    FROM prodlog_temp.log 
    WHERE mark = 'page updated'
    GROUP BY 
        date, 
        widget
    ORDER BY 
        date ASC, 
        actionCount DESC
    LIMIT 5 BY date
) 
GROUP BY date
LIMIT 10

Which was executed into client
http://joxi.ru/n2Yv7nNcjnPk0A

But into JDBC-driver i had error:
http://joxi.ru/DmBqenoHN8aqxr
(in Apache Zeppelin)

Version of driver - ru.yandex.clickhouse:clickhouse-jdbc:0.1.14

**Comment by TimonKK** [comment]
I tried with last version of driver (0.1.27), but nothing changed

**Comment by serebrserg** [comment]
Hello,
nested arrays are not supported yet
https://github.com/yandex/clickhouse-jdbc/issues/103

**Comment by zhicwu** [comment]
Nested arrays have been supported since v0.3.2, however, it is advisable to update to v0.4.6 or later for improved performance and bug fixes.

**Comment by zhicwu** [comment]
Nested arrays have been supported since v0.3.2, however, it is advisable to update to v0.4.6 or later for improved performance and bug fixes.
