### ISSUE TITLE
JSON fromat parsed as TabSeparated

### ISSUE THREAD

**Issue by mixNIK999** [ClickHouse/clickhouse-java#1310]
### Describe the bug
Query with JSON format retuns response with records witch are parsed as TabSeparated
Expected UnsupportedOperationException https://github.com/ClickHouse/clickhouse-java/blob/main/clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseStreamResponse.java#L147

### Steps to reproduce
1. Run new Clickhouse instance in docker
2. Run code below

### Expected behaviour
throw UnsupportedOperationException

### Code example
```java
class CHClientBug {
    public static void main(String[] args) throws ClickHouseException {
        ClickHouseNodes server = ClickHouseNodes.of("http://localhost:8123");
        try (ClickHouseClient client = ClickHouseClient.newInstance(ClickHouseProtocol.HTTP)) {
            try (ClickHouseResponse response = client.connect(server)
                    .format(ClickHouseFormat.JSON)
                    .query("select number from numbers(:limit)")
                    .params(1)
                    .executeAndWait()) {
                response.records().forEach(r -> r.forEach(System.out::println));
            }
        }
    }
}
```
### Error log
ClickHouseStringValue[{]
ClickHouseStringValue[	"meta":]
ClickHouseStringValue[	[]
ClickHouseStringValue[		{]
ClickHouseStringValue[			"name": "number",]
ClickHouseStringValue[			"type": "UInt64"]
ClickHouseStringValue[		}]
ClickHouseStringValue[	],]
ClickHouseStringValue[]
ClickHouseStringValue[	"data":]
ClickHouseStringValue[	[]
ClickHouseStringValue[		{]
ClickHouseStringValue[			"number": "0"]
ClickHouseStringValue[		}m]
ClickHouseStringValue[	]
	]
ClickHouseStringValue[]
ClickHouseStringValue[	"rows": 1,]
ClickHouseStringValue[]
ClickHouseStringValue[	"rows_before_limit_at_least": 1,]
ClickHouseStringValue[]
ClickHouseStringValue[	"statistics":]
ClickHouseStringValue[	{]
ClickHouseStringValue[		"elapsed": 0.001551,]
ClickHouseStringValue[		"rows_read": 1,]
ClickHouseStringValue[		"bytes_read": 8]
ClickHouseStringValue[	}]
ClickHouseStringValue[}]
#### Environment
* Client version: clickhouse-client-0.3.2-patch10
* Language version: Java 17
* OS: Mac OS Monterey

#### ClickHouse server
* ClickHouse Server version: 23.3.1.2823
* Empty DB runing in docker

**Comment by zhicwu** [comment]
Thanks for the report @mixNIK999. As of now, the lib does not support many data formats. Text-based data format like `JSON` are processed by line by default. Before a JsonDataProcessor is implemented, you may pass `response.getInputStream()` to Gson/Jackson for deserialization.

**Comment by mixNIK999** [comment]
Thank you for quick answer @zhicwu. I find current default behavior a little bit confusing. IMHO, client should signals somehow that current version doesn't support JSON deserialization and call `response.records()` is almost meaningless. Such [exception in code](https://github.com/ClickHouse/clickhouse-java/blob/main/clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseStreamResponse.java#L147) doubles this confusion

**Comment by zhicwu** [comment]
ClickHouse supports [multiple data formats](https://clickhouse.com/docs/en/interfaces/formats). In general, binary data format is more efficient compare to text-based format.

As of now, `RowBinaryWithNamesAndTypes` is fully supported but unfortunately others are not. Changing data format in ClickHouseRequest is low-level API which is probably too advanced as it requires additional work to get data deserialized, so I'd suggest you start with JDBC driver instead.

Lastly, as to `response.records()`, I have an idea of introducing popular object mapping framework(JMapper/MapStruct) to map row/record to Java object, but I never had a chance to do that. Would be great if you or someone has time to come up with a PR for that.
