### ISSUE TITLE
LZ4 is not supported. Please disable compression(compress=0)

### ISSUE THREAD

**Issue by jdAction** [ClickHouse/clickhouse-java#1317]
### Describe the bug
LZ4 is not supported. Please disable compression(compress=0), modify the algorithm(e.g. compress_algorithm=gzip), or add the missing libraries to the classpath., server ClickHouseNode [uri=http://192.168.43.135:8123/sifa_invoke_log]@-1010831720
### Steps to reproduce
1.docker run -d -p 9000:9000 -p 8123:8123 -p 9009:9009 --name clickhouse \
    -v /data/clickhouse/data:/var/lib/clickhouse/ \
    -v /data/clickhouse/log:/var/log/clickhouse-server/ \
    --ulimit nofile=262144:262144 clickhouse/clickhouse-server

### Expected behaviour
select clickhouse 
### Code example
```java
```
jdk11
        <dependency>
            <groupId>com.clickhouse</groupId>
            <artifactId>clickhouse-jdbc</artifactId>
            <version>0.4.4</version>
        </dependency>
### Cause: java.sql.BatchUpdateException: LZ4 is not supported. Please disable compression(compress=0), modify the algorithm(e.g. compress_algorithm=gzip), or add the missing libraries to the classpath., server ClickHouseNode [uri=http://192.168.43.135:8123/sifa_invoke_log]@-1010831720
; bad SQL grammar []; nested exception is java.sql.BatchUpdateException: LZ4 is not supported. Please disable compression(compress=0), modify the algorithm(e.g. compress_algorithm=gzip), or add the missing libraries to the classpath., server ClickHouseNode [uri=http://192.168.43.135:8123/sifa_invoke_log]@-1010831720] with root cause
#### Environment
* Client version: 23.3.1.2823
* Language version: jdk11
* OS:windows11

#### ClickHouse server
* ClickHouse Server version:23.3.1.2823
* ClickHouse Server non-default settings, if any:
* `CREATE TABLE` statements for tables involved:
* create database sifa_invoke_log;
create table sifa_invoke_log.scale_invoke_log
(
    id Nullable(Int64),
    scale_platform_resource_id Int64    DEFAULT 0,
    scale_transaction_id       Int64    DEFAULT 0,
    chain_account_name         String   DEFAULT '',
    chain_account_action_name  String   DEFAULT '',
    type                       tinyint  DEFAULT 1,
    http_status_code           Int16    DEFAULT 0,
    business_err_code          Int16    DEFAULT 0,
    create_time                DateTime DEFAULT toDateTime(now()),
    update_time                DateTime DEFAULT toDateTime(now())
)
    engine = MergeTree()
        order by create_time;
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary

**Comment by jdAction** [comment]
I revise config.xml this 
<compression>
    <case>
        <min_size>1024</min_size>
        <method>lz4</method>
        <min_ratio>0.5</min_ratio>
        <threads>0</threads>
    </case>
    </compression>
    error will still be reported

**Comment by zhicwu** [comment]
Do you have `lz4-java` in your classpath? Changing client option as stated in the error message should work too.

Please take a look at example at [here](https://github.com/ClickHouse/clickhouse-java/blob/main/examples/jdbc).

**Comment by jdAction** [comment]
I am developing in China, I am using the mybatis orm framework, I see that the configuration of this example is queryed using Statement, if I use mybatis, how should I set lz4?

**Comment by jdAction** [comment]
pom add this ?
 ```<classifier>http</classifier>

**Comment by zhicwu** [comment]
> pom add this ?
> ```
> <classifier>http</classifier>
> ```

Yes. Alternatively, you may add lz4 like below:

```xml
<dependency>
    <groupId>org.lz4</groupId>
    <artifactId>lz4-java</artifactId>
    <version>1.8.0</version>
</dependency>
```

**Comment by atepavicharov** [comment]
I've changed my connection string to use gzip and it worked
`jdbc:clickhouse:http://host:8123/db?compress_algorithm=gzip`
