### ISSUE TITLE
GRPC client is much slower than the HTTP client

### ISSUE THREAD

**Issue by ahmedriza** [ClickHouse/clickhouse-java#1325]
### Describe the bug
I was expecting the GRPC client to be as fast (if not faster) than the HTTP client.  However, my observation is that the GRPC client is about 4 times slower on a simple test.

### Steps to reproduce
1. Execute the very simple SQL: "select number from numbers(1000000)"
2. Use the GRPC client to execute the above query
3. Compared with the same query using the HTTP client, the result is around 3 times slower

On my setup, the HTTP client takes around 700 ms whereas the GRPC version takes over 3 seconds.

Clickhouse server logs when using the GRPC end point:
```
2023.04.23 20:39:03.476703 [ 1797766 ] {} <Information> GRPCServer: Handling call ExecuteQueryWithStreamIO()
2023.04.23 20:39:03.959291 [ 1797766 ] {7411c4d0-82d7-47cc-92a2-815beeaaad06} <Information> executeQuery: Read 1046544 rows, 7.98 MiB in 0.451344244 sec., 2318726 rows/sec., 17.69 MiB/sec.
2023.04.23 20:39:03.959483 [ 1797766 ] {} <Information> GRPCServer: Finished call ExecuteQueryWithStreamIO() in 0.482967942 secs. (including reading by client: 0.401670006, writing by client: 0.030488332)
```

Server logs when using the HTTP end point:
```
2023.04.23 20:39:27.333400 [ 1503278 ] {f9f46ae5-66cf-4167-acfa-72fc86e029c9} <Information> executeQuery: Read 1046544 rows, 7.98 MiB in 0.548288315 sec., 1908747 rows/sec., 14.56 MiB/sec.
```

Enabling compression (gzip) on the server side for the GRPC interface makes no difference.

### Expected behaviour
Same performance as HTTP or better when using the GRPC interface

### Code example
Full code example to demonstrate the issue.  Comment out the GRPC protocol and uncomment the HTTP protocol to test with the HTTP interface.
```java
import com.clickhouse.client.*;
import com.clickhouse.data.ClickHouseColumn;
import com.clickhouse.data.ClickHouseFormat;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.IntStream;

public class ClickHouseTest {

    public static void main(String[] args) {
        ClickHouseNode node = connect();
        execute(node);
    }

    static ClickHouseNode connect() {
        return ClickHouseNode.builder()
                             .host("example.com")
                             .port(ClickHouseProtocol.GRPC)
                             // .port(ClickHouseProtocol.HTTP)
                             .database("default")
                             .build();
    }

    static void execute(ClickHouseNode node) {
        try (ClickHouseClient client = ClickHouseClient.newInstance(node.getProtocol())) {
            ClickHouseRequest<?> request = client.read(node);

            var start = System.currentTimeMillis();
            try (ClickHouseResponse response = request
                    .format(ClickHouseFormat.RowBinaryWithNamesAndTypes)
                    .query("select number from numbers(1000000)").executeAndWait()) {
                var fields = response.getColumns().stream()
                                     .map(ClickHouseColumn::getColumnName)
                                     .toList();
                response.stream().forEach(record -> {
                    List<String> row = new ArrayList<>();
                    IntStream.range(0, fields.size())
                             .forEach(i -> row.add(record.getValue(i).asString()));
                    // Do something with the row
                });
            }
            var elapsed = System.currentTimeMillis() - start;
            System.out.println("Elapsed time: " + elapsed + " ms");
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
```

#### Environment
* Client version: 0.4.4
* Language version: JDK 17
* OS: Client is running on Mac OS 12.6.1

#### ClickHouse server
* ClickHouse Server version: 22.12.3.5
* OS: RHEL 8.6
* ClickHouse Server non-default settings, if any:

**Comment by zhicwu** [comment]
Thanks for the report @ahmedriza. I was expecting gRPC interface could be improved too. However, it's still an experimental feature not suitable for production usage. The only reason I keep gRPC client implementation here is for testing. It's probably better to move it to `examples` directory to demonstrate how to implement a custom client.

I believe the performance issue you found is related to `lz4`, which is the default compression algorithm used to decompress response from server. A workaround is to either disable compression or change compression algorithm to something else like `zstd` - see comparison at [here](/ClickHouse/ClickHouse/issues/28671#issuecomment-1403579952).

**Comment by zhicwu** [comment]
Changed label to question as it's a server side issue.

**Comment by ahmedriza** [comment]
@zhicwu thanks a lot for the information. I've tested with ZSTD compression and the results are now comparable to the HTTP interface.  Thanks.
