### ISSUE TITLE
Cannot update driver in Goland

### ISSUE THREAD

**Issue by Evgengrmit** [ClickHouse/clickhouse-java#1339]
Hi! I can't update the drivers for the clickhouse in Goland
### Error log
Download from maven failed

#### Environment
* Client version:
DBMS: ClickHouse (ver. 22.8.6.71)
Case sensitivity: plain=exact, delimited=exact
Driver: ClickHouse JDBC Driver (ver. 0.4.0 (revision: 3a53cf1), JDBC4.2)
* OS: MacOS

**Comment by zhicwu** [comment]
Just tried on GoLand 2023.1. The driver is 0.4.2 while the latest is 0.4.5, but I can download it without any issue. Perhaps you're having problem accessing Maven central? Regardless, you may manually download the driver from https://repo1.maven.org/maven2/com/clickhouse/clickhouse-jdbc/0.4.5/clickhouse-jdbc-0.4.5-http.jar and add it into GoLand.
