### ISSUE TITLE
can't create sessions via dbeaver 

### ISSUE THREAD

**Issue by VeryFunnyMan** [ClickHouse/clickhouse-java#1347]
I asked this question [here ](https://github.com/ClickHouse/ClickHouse/issues/49219)but got redirected here

I specify session_id and session_timeout in the driver properties through dbeaver, but when I try to `CREATE TEMPORARY TABLE ...` I still get the error "There is no session or session context has expired".

If using http I execute a request, write session_id and session_timeout, then a temporary table is created.

`http://host:port/?user=user&password=password&session_id=session_id&session_timeout=600&database=database&query=CREATE%20TEMPORARY%20TABLE...`
how to fix it?

clickhouse 22.9.3.18 on ubuntu 22.04
Standard clickhouse driver com.clickhouse:clickhouse-jdbc:RELEASE 0.3.2
dbeaver 22.2.1.202209251341
win10 21H2
I have full permissions

**Comment by zhicwu** [comment]
Hi @VeryFunnyMan, it could be an issue in the JDBC driver you're using.

Can you upgrade the driver to a more recent version like 0.4.6 which was released yesterday? Upgrade DBeaver helps too as it will suggest you upgrade the driver to 0.4.x.

**Comment by VeryFunnyMan** [comment]
it helped me, thanks
