### ISSUE TITLE
jdk returned serialized bitmap value is different from SQL result from server

### ISSUE THREAD

**Issue by gcqst** [ClickHouse/clickhouse-java#1371]
### Describe the bug
I use BinaryStreamUtils.writeBitmap to generated bitmap result and encode it to base64, but the result is different from sql result. Any suggestion?

### Steps to reproduce
1. see below code

### Expected behaviour
returned result should be same from scala and sql

### Code example
```scala
val data = List(533042119L, 585563069L, 966003955L, 505128622L)
val output = new ByteArrayOutputStream()
Roaring64NavigableMap.SERIALIZATION_MODE = 1
val bitmap = ClickHouseBitmap.wrap(Roaring64NavigableMap.bitmapOf(data:_*), ClickHouseDataType.UInt64)
BinaryStreamUtils.writeBitmap(output, bitmap)
val result = Base64.getEncoder.encodeToString(output.toByteArray)
println(result)
```

```sql
SELECT base64Encode(toString(bitmapBuild([
toUInt64(4294967297),toUInt64(4294967298),toUInt64(4294967299),toUInt64(4294967300)
])));
```
### Error log
scala result: 
AASuphseAAAAAMeTxR8AAAAAvfvmIgAAAADzDJQ5AAAAAA==

SQL result
   ┌─base64Encode(toString(bitmapBuild(array(toUInt64(533042119), toUInt64(585563069), toUInt64(966003955), toUInt64(505128622)))))─┐
1. │ AATHk8UfAAAAAL375iIAAAAA8wyUOQAAAACuphseAAAAAA==                                                                               │
   └────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
**AASuphseAAAAAMeTxR8AAAAAvfvmIgAAAADzDJQ5AAAAAA==** is not equal to **AATHk8UfAAAAAL375iIAAAAA8wyUOQAAAACuphseAAAAAA==**
#### Environment
* Client version: 0.4.6
* Language version: scala 2.12.12
* OS: macos
* dependency
```
<!-- https://mvnrepository.com/artifact/com.clickhouse/clickhouse-data -->
        <dependency>
            <groupId>com.clickhouse</groupId>
            <artifactId>clickhouse-data</artifactId>
            <version>0.4.6</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/com.clickhouse/org.roaringbitmap -->
        <dependency>
            <groupId>com.clickhouse</groupId>
            <artifactId>org.roaringbitmap</artifactId>
            <version>1.9.1</version>
        </dependency>
```

#### ClickHouse server
* ClickHouse Server version: 22.3-011

**Comment by zhicwu** [comment]
Hi @gcqst, you seem to be comparing two different values: a serialized bitmap in Java and the actual value stored in ClickHouse. It might be better to compare values within ClickHouse, as shown below, or compare two deserialized bitmaps outside of it.

```java
Properties props = new Properties();
try (ClickHouseConnection conn = newConnection(props);
        ClickHouseStatement stmt = conn.createStatement()) {
    stmt.execute("drop table if exists test_bitmap64_values; "
            + "create table test_bitmap64_values(id Int32, bm AggregateFunction(groupBitmap, UInt64))engine=Memory; "
            + "insert into test_bitmap64_values "
            + "select 1, groupBitmapState(a) "
            + "from (select arrayJoin([533042119,585563069,966003955,505128622]::Array(UInt64)) a)");
    try (PreparedStatement ps = conn.prepareStatement("insert into test_bitmap64_values")) {
        ps.setInt(1, 2);
        ps.setObject(2, ClickHouseBitmap.wrap(533042119L, 585563069L, 966003955L, 505128622L));
        Roaring64NavigableMap.SERIALIZATION_MODE = Roaring64NavigableMap.SERIALIZATION_MODE_PORTABLE;
        ps.executeUpdate();
    }

    ClickHouseBitmap bitmap1 = null;
    ClickHouseBitmap bitmap2 = null;
    try (ResultSet rs = stmt.executeQuery("select * from test_bitmap64_values order by id")) {
        Assert.assertTrue(rs.next(), "Should have at least one row");
        Assert.assertEquals(rs.getInt(1), 1);
        Assert.assertNotNull(bitmap1 = (ClickHouseBitmap) rs.getObject(2));
        Assert.assertTrue(rs.next(), "Should have at least one row");
        Assert.assertEquals(rs.getInt(1), 2);
        Assert.assertNotNull(bitmap2 = (ClickHouseBitmap) rs.getObject(2));
        Assert.assertFalse(rs.next(), "Should have only one unique row");
        Assert.assertEquals(bitmap1, bitmap2);
    }
}
```

**Comment by gcqst** [comment]
Thanks a lot @zhicwu 
I want to build bitmap result using encode64 string from offline pipeline and import it to CK bitmap by deserialize this string.
I compared encoded string previously, sometimes its different. And I found the elements in CK bitmap is same just with different ordering. It's OK to me.
I think maybe the different ordering cause those two encoded64 string are not same.
