### ISSUE TITLE
When the addBatch method encounters an error, the writePosition of ClickHouseDataProcessor is not reset to 0, causing the next execution of addBatch to start from an incorrect writePosition.

### ISSUE THREAD

**Issue by ibufu** [ClickHouse/clickhouse-java#1373]
### Describe the bug
When the addBatch method encounters an error, the writePosition of ClickHouseDataProcessor is not reset to 0, causing the next execution of addBatch to start from an incorrect writePosition.
### Steps to reproduce
1. Make an error in a loop of addBatch
2. 
3.

### Expected behaviour
When the addBatch method encounters an error, the writePosition of ClickHouseDataProcessor should reset to 0.
### Code example
```java
for (int i = 0; i < 2; i ++) {
    try {
        ps.setTimestamp(1, new Timestamp(value.getTime()));
        ps.setString(2, "1");
        ps.setString(3, i == 0 ? null : "1");
        ps.addBatch();
    } catch (SQLException e) {
    }
}
```
The first error of `Cannot set null to non-nullable column #3` is caught. We expect the second addBatch should run successfully. However, there is an error in the second addBatch.
### Error log
java.time.format.DateTimeParseException: Text '1' could not be parsed at index 0
	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949)
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851)
	at java.time.LocalDateTime.parse(LocalDateTime.java:492)
	at com.clickhouse.data.value.ClickHouseStringValue.asDateTime(ClickHouseStringValue.java:208)
	at com.clickhouse.data.format.BinaryDataProcessor$DateTime64SerDe.serialize(BinaryDataProcessor.java:291)
	at com.clickhouse.data.ClickHouseDataProcessor.write(ClickHouseDataProcessor.java:593)
	at com.clickhouse.jdbc.internal.InputBasedPreparedStatement.addBatch(InputBasedPreparedStatement.java:345)
#### Environment
* Client version: 0.4.6
* Language version: Java 8
* OS: Mac

#### ClickHouse server
* ClickHouse Server version:
* ClickHouse Server non-default settings, if any:
* `CREATE TABLE` statements for tables involved:
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary

**Comment by zhicwu** [comment]
Thanks @ibufu for reporting the issue. Yes, `resetDataProcessor()` should be able call. Will raise a PR to fix this along with a few more tests.

**Comment by ibufu** [comment]
Hi, @zhicwu ! Any suggestions for handling above exceptions before you fix the bug? Thanks!
