### ISSUE TITLE
jpa batch insert : Code: 26. DB::ParsingException: Cannot parse quoted string: expected opening quote ''', got '\'

### ISSUE THREAD

**Issue by liangxw5** [ClickHouse/clickhouse-java#1388]
1.error info:
ClickHouse exception, code: 1002, host: 192.168.1.200, port: 19102; Code: 26. DB::ParsingException: Cannot parse quoted string: expected opening quote ''', got '\': 
Row 1:
Column 4,   name: xxxxx,             type: Array(String), parsed text: "["ERROR
Code: 26. DB::ParsingException: Cannot parse quoted string: expected opening quote ''', got '\'. (CANNOT_PARSE_QUOTED_STRING) (version 22.1.3.7 (official build))

2.env:
2.1:springboot data jpa
2.2.datasouce:druid
2.3.clickhouse-jdbc:0.2.6

3.desciption
when I close jpa batch insert , sql executed success,
but I open jpa batch insert,sql executed fail.the error info is above.

List(String) type convert to Array(String),I use a converter:

```
@Converter
public class StringArrayToListConverter implements AttributeConverter<List<String>, String> {

    @Override
    public String convertToDatabaseColumn(List<String> attribute) {
        if (Collections.isEmpty(attribute)) {
            return "[]";
        }
        return attribute.stream()
                .map(s -> "'" + s.replaceAll("'", "''") + "'")
                .collect(Collectors.joining(", ", "[", "]"));
    }

    @Override
    public List<String> convertToEntityAttribute(String dbData) {
        if (StringUtils.isBlank(dbData)) {
            return Lists.newArrayList();
        }
        return JSONArray.parseObject(dbData, new TypeReference<List<String>>() {
        });
    }
} 
```

duo to the business needed,batch insert is necessary.please give me a solution to resovle this problem,thanks.

**Comment by zhicwu** [comment]
Hi @liangxw5, thanks for the report. It could be an issue in legacy driver when handling batch insert. Have you tried upgrading driver to 0.4.6?

**Comment by liangxw5** [comment]
@zhicwu I use the Driver's groupId is : ru.yandex.clickhouse, tried upgrading driver to 0.3.2.but it's not effective.
now I will try to use com.clickhouse,thinks for your advice,please wait.

**Comment by liangxw5** [comment]
@zhicwu Hi,I tried to use 0.4.6 version.but I encountered a new problem:
Error attempting to apply AttributeConverter; nested exception is javax.persistence.PersistenceException: Error attempting to apply AttributeConverter


I guess the problem is the StringArrayToListConverter . because I tried to delete the List<String> field.It successed.
```
    @Column(name = "names")
    @Convert(converter = StringArrayToListConverter.class)
    private List<String> nameList;
```
Please check it for me，thanks.my converter is below:

```
@Converter
public class StringArrayToListConverter implements AttributeConverter<List<String>, String> {

    @Override
    public String convertToDatabaseColumn(List<String> attribute) {
        if (Collections.isEmpty(attribute)) {
            return "[]";
        }
        return attribute.stream()
                .map(s -> "'" + s.replaceAll("'", "''") + "'")
                .collect(Collectors.joining(", ", "[", "]"));
    }

    @Override
    public List<String> convertToEntityAttribute(String dbData) {
        if (StringUtils.isBlank(dbData)) {
            return Lists.newArrayList();
        }
        return JSONArray.parseObject(dbData, new TypeReference<List<String>>() {
        });
    }
} 

```

**Comment by liangxw5** [comment]
@zhicwu there is a new problem,when i insert a Ring,java type is List<Point>:
Caused by: java.lang.UnsupportedOperationException: Converting [String] to [Ring] is not supported

when I use the driver [ru.yandex.clickhouse],the problem has  never occurred .

**Comment by zhicwu** [comment]
Sorry it didn't work for you. Can we use `String[]` for Array(String) and `double[][]` for Ring?

Taking Array(String) as an example, you may refer to below test in clickhouse-jdbc module:

https://github.com/ClickHouse/clickhouse-java/blob/c25ffc62c886c0cdc1fcf8d8bf2234690c131dca/clickhouse-jdbc/src/test/java/com/clickhouse/jdbc/ClickHousePreparedStatementTest.java#L1680C12-L1698

**Comment by liangxw5** [comment]
My project uses springboot framwork,and DAO uses spring data jpa.
Due to the business,List type is necessary.

**Comment by zhicwu** [comment]
> List type is necessary.

Understood. Have you tried to add a new converter to convert `List<String>` to `String[]`?
