### ISSUE TITLE
Support custom socket factory

### ISSUE THREAD

**Issue by zhicwu** [ClickHouse/clickhouse-java#1391]
As requested at https://github.com/ClickHouse/clickhouse-java/pull/1171#discussion_r1248335413

**Comment by mayankvadariya** [comment]
:tada: Thanks much @zhicwu  for creating this issue. I will keep an eye to see when this gets closed.

**Comment by mayankvadariya** [comment]
Thanks @zhicwu for working on this feature. Can we release this feature?

**Comment by mayankvadariya** [comment]
@mzitnik, can you or @zhicwu help to release this feature?

**Comment by mayankvadariya** [comment]
@zhicwu @mzitnik checking again here if this feature can be released?

**Comment by mzitnik** [comment]
@mayankvadariya Sorry for the delay. We are working on that having some issues in our release process. You can bypass it for now by building a local version. Again sorry for the delay

**Comment by zhicwu** [comment]
> @mayankvadariya Sorry for the delay. We are working on that having some issues in our release process. You can bypass it for now by building a local version. Again sorry for the delay

Hopefully I can fix the issues in `nightly` and `release` two workflows in the weekend.

**Comment by mayankvadariya** [comment]
@zhicwu @mzitnik do you have any update on the release timeline?
