### ISSUE TITLE
The return value of client.write(...).executeAndWait()  method returns an incorrect result

### ISSUE THREAD

**Issue by Dong-GuoSheng** [ClickHouse/clickhouse-java#1414]
### Describe the bug
client.write(……).executeAndWait()方法返回值在忽略错误情况下结果不正确，版本0.4.6

### Steps to reproduce
1.create tablet test.t1
```
CREATE TABLE test.t1
(
    `a` String,
    `b` String
)
ENGINE = MergeTree
ORDER BY a
```

2. vim a.tsv
zs	ls
ww
zl	zl

3. load data to table
```
ClickHouseNode server = ClickHouseNode.of("http://127.0.0.1:8123/test");
ClickHouseFile file = ClickHouseFile.of("/home/dss/Desktop/a.tsv");
ClickHouseClient client = ClickHouseClient.builder().nodeSelector(ClickHouseNodeSelector.of(null, server.getProtocol())).config(server.getConfig()).build();
try {
    ClickHouseResponse response = client.write(server).table("test.t1").data(file).set("input_format_allow_errors_num", 100).executeAndWait();
    System.out.println(response.getSummary());
} catch (Exception e) {
    e.printStackTrace();
}
```

4. view the result：
System.out.println(response.getSummary());
ClickHouseResponseSummary [readBytes=0, readRows=0, totalRowsToRead=0, writtenBytes=0, writtenRows=0, updates=0]

5.In fact, 2 rows of data were successfully written.

### Code example
```java
```
#### Environment
* Client version: 0.4.6
* Language version:
* OS:Deepin OS

#### ClickHouse server
* ClickHouse Server version:22.2.2.1
* ClickHouse Server non-default settings, if any:
* `CREATE TABLE` statements for tables involved:
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary

**Comment by Dong-GuoSheng** [comment]
通过“select event_time,query,result_rows from system.query_log where event_date='2023-08-03' and query_kind='Insert' and type='QueryFinish' ”，也能确认results_rows为2。
所以返回的结果不正确。

**Comment by zhicwu** [comment]
Hi @Dong-GuoSheng, did you resolve the issue? I cannot reproduce at my end. And it's suggested to close response object timely, for example:
```java
try (ClickHouseResponse response = client.write(server).table("test.t1")
  .data(file).set("input_format_allow_errors_num", 100).executeAndWait()) {
     System.out.println(response.getSummary());
}
```
Apart from that, ClickHouse 22.2 is not a supported version, could you try LTS version like 22.8 or 23.3?

**Comment by Dong-GuoSheng** [comment]
> Hi @Dong-GuoSheng, did you resolve the issue? I cannot reproduce at my end. And it's suggested to close response object timely, for example:
> 
> ```java
> try (ClickHouseResponse response = client.write(server).table("test.t1")
>   .data(file).set("input_format_allow_errors_num", 100).executeAndWait()) {
>      System.out.println(response.getSummary());
> }
> ```
> 
> Apart from that, ClickHouse 22.2 is not a supported version, could you try LTS version like 22.8 or 23.3?

yes, i just tested it in 22.8 version and it works fine!
thanks.
