### ISSUE TITLE
Remove deprecated API and settings 

### ISSUE THREAD

**Issue by mshustov** [ClickHouse/clickhouse-java#1424]
Remove deprecated:
- [use_no_proxy]( https://github.com/ClickHouse/clickhouse-java/blob/f3c64de1af71fd4e3f781f16f52c4033fd728bc5/clickhouse-client/src/main/java/com/clickhouse/client/config/ClickHouseClientOption.java#L376) and appropriate [API](https://github.com/ClickHouse/clickhouse-java/blob/f3c64de1af71fd4e3f781f16f52c4033fd728bc5/clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseConfig.java#L653)
- deprecated  versions of `dump` , `load` https://github.com/ClickHouse/clickhouse-java/blob/0f95633af4bd971d7156079351875704fd5396fa/clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseClient.java

**Comment by mzitnik** [comment]
@zhicwu By removing use_no_proxy from config, we also remove it from GRPC https://github.com/ClickHouse/clickhouse-java/blob/32a8bf00d19eadf1e14e3f66041752c4f4dbd5fc/clickhouse-grpc-client/src/main/java/com/clickhouse/client/grpc/ClickHouseGrpcChannelFactory.java#L196

**Comment by mzitnik** [comment]
@mshustov there is another API `connect` that also can be removed https://github.com/ClickHouse/clickhouse-java/blob/0f95633af4bd971d7156079351875704fd5396fa/clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseClient.java#L918C1-L918C1

**Comment by mzitnik** [comment]
PR https://github.com/ClickHouse/clickhouse-java/pull/1433
