### ISSUE TITLE
ClickHouse JDBC Date type limit differ from ClickHouse documentation

### ISSUE THREAD

**Issue by hanzomaster** [ClickHouse/clickhouse-java#1426]
When I'm migrating to ClickHouse, I found out that in the source code ClickHouse JDBC (version 0.4.6) set the limit for Date32 data type is from `1925-01-01` to `2283-11-11`.
```java
public static final int DATE32_MAX = (int)LocalDate.of(2283, 11, 11).toEpochDay();
public static final int DATE32_MIN = (int)LocalDate.of(1925, 1, 1).toEpochDay();
```
However, in the ClickHouse docs for `Date32` [here](https://clickhouse.com/docs/en/sql-reference/data-types/date32). It said that the data range is same as `DateTime64` which is from `1900-01-01` to `2299-12-31` as shown [here](https://clickhouse.com/docs/en/sql-reference/data-types/datetime64). Is this a mistake or am I missing something here?

**Comment by zhicwu** [comment]
Hi @hanzomaster, thanks for the report. The driver should be enhanced for sure, and I believe the official doc for Date32 is inaccurate too.

```sql
SELECT toDate32('2283-11-11') currentMaxDate, currentMaxDate + INTERVAL 10 DAY d1,
	toDate32('1925-01-01') currentMinDate, currentMaxDate - INTERVAL 10 DAY d2,
	toDate32('9999-99-99') maxDate, toDate32('0000-00-00') minDate,
	toDate32(toUInt32(-1)) testDate, toUInt32(testDate) i

currentMaxDate|d1        |currentMinDate|d2        |maxDate   |minDate   |testDate  |i    |
--------------+----------+--------------+----------+----------+----------+----------+-----+
    2283-11-11|2283-11-21|    1925-01-01|2283-11-01|1900-01-01|1900-01-01|2106-02-07|49710|
```
