### ISSUE TITLE
How to get ResultSetMetaData in ClickHousePreparedStatement

### ISSUE THREAD

**Issue by suhli** [ClickHouse/clickhouse-java#1430]
Is there any way to get the result set metadata without execution like issue #235 ?
I check codes main branch, seems like the [reference file change](https://github.com/ClickHouse/clickhouse-java/pull/288/commits/ae44bba57a3b27a3bd05fca5a3d10db8eb770892) ClickHousePreparedStatementImpl.java with PR #288  has been deprecated

**Comment by zhicwu** [comment]
Hi @suhli, could you share the use case? Did you mean `ParameterMetaData`?

**Comment by suhli** [comment]
> Hi @suhli, could you share the use case? Did you mean `ParameterMetaData`?

I'm using [Trino](https://github.com/trinodb/trino) as middleware provides the ability to query across different databases.
Yet in some cases, I need to pass the original sql to upstream databases. eg: some json query(Trino will not pushdown filter in some case)
I found the following comments in Trino clickhouse testcase that describe the reason(it has been delete in main branch,yet still not support):
> // table function disabled for ClickHouse, because it doesn't provide ResultSetMetaData, so the result relation type cannot be determined

[support native](https://github.com/trinodb/trino/commit/daa6bba44986921d0a70d6fc23e23207beed5bc1#diff-74f60487e733f50e5b75b579f6a4927e7a0c0a10e741f3dec1ed84be2fe5e502R83-R84)

[reason](https://github.com/trinodb/trino/commit/daa6bba44986921d0a70d6fc23e23207beed5bc1#diff-74f60487e733f50e5b75b579f6a4927e7a0c0a10e741f3dec1ed84be2fe5e502L666)

**Comment by zhicwu** [comment]
Thank you for the additional context.  Since this is for a push-down query, it would not be ideal to execute the full query just to retrieve the ResultSetMetaData for type inference. Actually I'm also concerned about when to release ResultSet in the original fix. Anyway, as an optimization, we could use`desc (<original query>)` instead. I'll fix this tonight along with other minor issues.

**Comment by sylph-eu** [comment]
Should be addressed by #1700
