### ISSUE TITLE
Batch insert, gives warning when add multiple rows to one insert

### ISSUE THREAD

**Issue by usatenko** [ClickHouse/clickhouse-java#1432]
### Describe the bug
It is more a question, not sure if it is a bug

### Steps to reproduce
1. Create prepared statement "insert into table (v1, v2, v3) values (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?)"
2. You will get a warning "Please consider to use one and only one values expression, for example: use 'values(?)' instead of 'values(?),(?)'."
3. What's wrong with this option? Please note, that ClickHouse recommends doing it exactly this way.

### Expected behavior
Just no warning is expected

#### Environment
* Client version: com.clickhouse, clickhouse-jdbc, 0.4.6
* Language version: openjdk version "17.0.9-ea"
* OS: Linux Debian x86_64

clickhouse-jdbc/src/main/java/com/clickhouse/jdbc/internal/SqlBasedPreparedStatement.java
<img width="996" alt="image" src="https://github.com/ClickHouse/clickhouse-java/assets/1710344/0de04c5b-e087-4438-8b49-4aa81b27e599">

**Comment by usatenko** [comment]
If I do the "ps.executeBatch();", is it executed internally as:
1) a long insert like "insert into table values (?, ?, ?), (?, ?, ?)" or
2) a series of many "insert into table values (?, ?, ?)"
and if it is the (2) option, may it decrease the performance compared to inserting it as a (1) option?
Assuming we may insert up to 5k rows at a time?

**Comment by janson653** [comment]
any update?

**Comment by den-crane** [comment]
> If I do the "ps.executeBatch();", is it executed internally as:
> 
>     1. a long insert like "insert into table values (?, ?, ?), (?, ?, ?)" or

a long insert , all values will added within one insert.
