### ISSUE TITLE
Query settings session_timezone not being applied

### ISSUE THREAD

**Issue by tecpcarrier** [ClickHouse/clickhouse-java#1464]
### Describe the bug
Clickhouse allows user to set query to multiple level including at the query level. When the setting `session_timezone` is set in dbeaver , the setting is not being picked up. I have looked at this issue #604 where the timezone is set correctly for `toDateTime` but it does not seem to be the case when using this setting. Whenever I use `session_timezone`, the datetime uses the wrong timezone.

![image](https://github.com/ClickHouse/clickhouse-java/assets/146966511/1a186506-6976-4fbc-884e-d9c6b837ed31)

In this query, the date should be identical to the second column not the third. Running it directly using `clickhouse-client`, the result of this query should be the following:

![image](https://github.com/ClickHouse/clickhouse-java/assets/146966511/d2083235-2116-443e-969a-cadf47ee2549)

By changing the `session_timezone`, the value in the first column should change to adapt to the new timezone.

#### ClickHouse server
* ClickHouse Server version: 23.8.2.7
* Statement:
```
WITH temp AS
    (
        SELECT 1696431276 AS date
    )
SELECT
    toDateTime(date),
    toDateTime(date, 'America/New_York'),
    toDateTime(date, 'UTC')
FROM temp
SETTINGS session_timezone = 'America/Vancouver'
```

**Comment by mohaidoss** [comment]
Hey any workaround @tecpcarrier ? I am having the same issue, and it's quite confusing since the following test is doing just fine with the JDBC...

```sql
SELECT toDateTime('2023-01-01 10:15:20') SETTINGS session_timezone = 'Etc/GMT+5'
```
![image](https://github.com/ClickHouse/clickhouse-java/assets/48034655/788eca17-d1f6-41ea-9464-7e1e8160d613)

**Comment by vladaman** [comment]
We are experiencing same issue. Seems like `SETTINGS session_timezone = 'Etc/GMT+5'` has no effect on result.

**Comment by den-crane** [comment]
The reason is in Clickhouse server
* https://github.com/ClickHouse/ClickHouse/issues/63359

**Comment by mohaidoss** [comment]
@den-crane seems like the bug is fixed on versions `>= 23.8` ?

**Comment by chernser** [comment]
@mohaidoss There is a bug on client side - value from the server timezone header is not applied to results (only for RowBinary*) 
I'm working on the fix.

**Comment by chernser** [comment]
Client today doesn't read `X-Server-Timezone` from a response. Besides that `toDateTime('2023-10-04 10:54:36')` uses server timezone anyway even if `session_timezone` specified: 

```
SELECT
    toDateTime('2023-10-04 10:54:36'),
    serverTimezone(),
    timezone(),
    toDateTime('2023-10-04 10:54:36', 'UTC')
SETTINGS session_timezone = 'America/Los_Angeles'

Query id: d78c4447-fe88-40e4-9a61-7033f2069cb2

   ┌─toDateTime('2023-10-04 10:54:36')─┬─serverTimezone()─┬─timezone()──────────┬─toDateTime('2023-10-04 10:54:36', 'UTC')─┐
1. │               2023-10-04 10:54:36 │ UTC              │ America/Los_Angeles │                      2023-10-04 10:54:36 │
   └───────────────────────────────────┴──────────────────┴─────────────────────┴──────────────────────────────────────────┘
```

After the fix about the header client would convert all `DateTime` values that come without an offset into server timezone that is returned in response. However it will not affect values that have timezone already. 
And this behavior will work only if client is configured to use server timezone.

**Comment by mohaidoss** [comment]
Thats Exciting @chernser. Let le know if I can be of help :)
