### ISSUE TITLE
String parameter not escaped

### ISSUE THREAD

**Issue by JamieD9** [ClickHouse/clickhouse-java#1465]
### Describe the bug
When querying a table with a bind parameter the caller must both quote a string argument & escape any single quotes.

### Steps to reproduce
With 0.4.6 running a query against any table with a single String parameter
```
var name =  "Robert'); DROP TABLE Students;--";
client.read(server)
                    .format(ClickHouseFormat.RowBinaryWithNamesAndTypes)
                    .query("select * from my_table where name = :name(String)")
                    .params(Map.of("name", name))
                    .execute().get();
```
Fails as the string is dropped into the location of the :name parameter, a bit like `String.format("%s");`
Replacing the query with 
```
 .query("select * from my_table where name = ':name(String)'")
```
Sends the query to the DB with ':name(String)' as the value.

Supplying the parameter as 
```
 name = "'" + name.replace("'", "''") + "'";
```
Sort of works but feels quite clunky.

### Expected behaviour
The provided parameter should be sent to the CH backend as a parameter (if possible) or escaped if that is not possible.
If there are unused query parameters an error should be thrown (perhaps configurable?).

#### ClickHouse server
* ClickHouse Server version: 23.3.13.6
* `CREATE TABLE` statements for tables involved:
```
                    create table if not exists my_table
                    (
                        name String,
                        dttm timestamp not null
                    )  engine=MergeTree() order by name;
```

**Comment by panthony** [comment]
Encountered the same issue using `ClickHouseParameterizedQuery.apply` where I do

```sql
WHERE query_id = :id(String)
```

And the query failed with:

> DB::Exception: Missing columns: '8d46' 'b6a0e832' '4ea8' '8a41' '54719a110fb4'

Because the string value is not in quotes.

I also add to dig within the code of the java client itself because I saw no mention of this notation `:var(Type)` on this page:

https://clickhouse.com/docs/en/integrations/java#query

Not sure if there is a dedicated documentation somewhere that I could not find 🤔

**Comment by mshustov** [comment]
@mzitnik when you work on the issue, you can take a look at Python client implementation https://github.com/ClickHouse/clickhouse-connect/blob/6928aed5845c944007b6bf93e806313a96a93fbc/clickhouse_connect/driver/query.py#L431-L435

**Comment by BentsiLeviav** [comment]
Hi @panthony, @JamieD9 

The `params` function offers multiple signatures. All signatures involving `String` as parameter values (e.g., `Map<String, String>`) expect valid ClickHouse SQL expressions.

The remaining signatures handle conversion (escaping and validation) within the `params` function. Therefore, it is recommended to use the `ClickHouseValues.convertToSqlExpression` helper, which manages all the necessary conversion and validation.


```
try (ClickHouseClient client = ClickHouseClient.newInstance(server.getProtocol());
                 ClickHouseResponse response = client.read(server)
                         .format(ClickHouseFormat.RowBinaryWithNamesAndTypes)
                         .query("select * from my_table where string_column=:name")
                         .params(Map.of("name", ClickHouseValues.convertToSqlExpression("sdf'sdf"))).execute().get()) {}
```

We are actively working on providing a more robust parameter mechanism, which will be part of a major release in the future.

In addition, I've updated the documentation about this matter at ClickHouse/clickhouse-docs#1794

@JamieD9, regarding your example (apart from this parameter issue), as far as I know, the native client doesn't allow running multiple statements in one query, so you will likely encounter an error.

**Comment by JamieD9** [comment]
Hi,

Thanks for the update, we name our parameters and it's a bit of a shame to assume the order is correct (given they are named). Is it possible to add a method that correctly applies the named parameters? I also assume the ClickHouse server can apply query plan caching _before_ resolving parameters & so resolving them on the client would not be ideal, is this not the case?

Finally
`ClickHouseValues.convertToSqlExpression` seems a little suspect to me:

```
        } else if (value instanceof Enum) {
            s = String.valueOf(((Enum<?>) value).ordinal()); // faster than escaped name
```
My understanding would be that if I have an enum with `Dog, Cat` then later add `Unknown, Dog, Cat` all my values will be incorrect, also queries outside of Java will not be aware of the enum labels, would you agree? We tend to declare enum columns as `LowCardinality(String)` and hope that during serialisation repeated column values get compressed.

**Comment by BentsiLeviav** [comment]
Hi @JamieD9 

> we name our parameters and it's a bit of a shame to assume the order is correct (given they are named). Is it possible to add a method that correctly applies the named parameters?

What do you mean? this method is not an order based.
`params` accepts a Map of parameters, therefore **there is no reason to worry about parameters order**

For instance, these two examples will work the same way (with different parameters order):
![image](https://github.com/ClickHouse/clickhouse-java/assets/46030906/6bb1da10-9778-4f98-9b32-38fcfb503316)
![image](https://github.com/ClickHouse/clickhouse-java/assets/46030906/b3f0832b-62cc-4356-bd0f-42438faefe7e)

> I also assume the ClickHouse server can apply query plan caching before resolving parameters & so resolving them on the client would not be ideal, is this not the case?

That is correct. This is the parameter mechanism refactor I mentioned previously (I created a dedicated issue #1517 . Feel free to add ideas there).

> We tend to declare enum columns as LowCardinality(String)

The conversion code you quoted maps between Java Enum to [Clickhouse Enum](https://clickhouse.com/docs/en/sql-reference/data-types/enum). A `LowCardinality(String)` field is expecting to get a regular `String`, therefore, I would recommend you convert your Java Enum to a string before inserting it into a String column as the regular Enum conversion is meant for ClickHosue Enum.
