### ISSUE TITLE
Java 11 HttpClient connection is not reusable

### ISSUE THREAD

**Issue by john9x** [ClickHouse/clickhouse-java#1492]
https://github.com/ClickHouse/clickhouse-java/blob/6a0856fdc4dbfed89dd2d0030f20accdec63bce8/clickhouse-http-client/src/main/java11/com/clickhouse/client/http/HttpClientConnectionImpl.java#L206

I suspect there is a bug. It should be `return !busy.get();` IMHO

**Comment by mzitnik** [comment]
@john9x Can you describe the issue that you have encountered just as background?

**Comment by john9x** [comment]
@mzitnik I have use clickhouse-jdbc with Hikari connection pool and I see that underlying HTTP connection establishing every time when I get connection from pool. 
```
http_connection_provider=HTTP_CLIENT
```

**Comment by mzitnik** [comment]
What version of `clickhouse-jdbc` you are using

**Comment by john9x** [comment]
```
<dependency>
            <groupId>com.clickhouse</groupId>
            <artifactId>clickhouse-jdbc</artifactId>
            <version>0.5.0</version>
            <classifier>http</classifier>
</dependency>
```

**Comment by mzitnik** [comment]
Why are you using `http_connection_provider=HTTP_CLIENT` and not the default one?

**Comment by mzitnik** [comment]
HTTP_CLIENT was an experimental. 
We are planning to deprecate the support for HTTP_CLIENT in the next version.
So thanks for pointing it out
