### ISSUE TITLE
i find that there are two types of clients, I have a lot of write requests, which is more efficient?

### ISSUE THREAD

**Issue by z7658329** [ClickHouse/clickhouse-java#1501]
**1. my first question:**

use jdbc：
https://github.com/ClickHouse/clickhouse-java/blob/main/examples/jdbc/src/main/java/com/clickhouse/examples/jdbc/Basic.java

use client:
https://github.com/ClickHouse/clickhouse-java/blob/main/examples/client/src/main/java/com/clickhouse/examples/jdbc/Main.java

I have a lot of write requests, and need to write in batch mode,  so  which is more efficient?  can  any one tell me, thanks!

**2. my second question:**
dose client support config retry count ?  i want retry 3 times when write to ck error

**Comment by chernser** [comment]
@z7658329 
as far as I may see from their code and documentation: 
* just client  - is client abstraction of  http/file/grpc client. It is not wrapped with JDBC API 
* jdbc - is "just client" wrapped with JDBC

Performance will depend on your use case and the destination your are writing to. Would you describe it more?
