### ISSUE TITLE
Load balancing/Failover using ClickHouseNodes doesn't seem to work.

### ISSUE THREAD

**Issue by simojenki** [ClickHouse/clickhouse-java#1502]
### Describe the bug
It appears that load balancing/failover using ClickHouseNodes doesn't work.  Alternatively I am not using it properly, in which case if someone could point me at a working example that would be good.

I had expected to be able to create an instance of ClickHouseNodes using endpoints like 'http://host1,host2,host3:8123' and to then have the ClickHouseNodes instance manage whether each host/node is available and only return available host/nodes when asked.  It certainly looks like that is the intent of the code within ClickHouseNodes.

### Steps to reproduce
1. start up clickhouse-examples/docker-compose-recipes/recipes/cluster_1S_2R
2. shut down clickhouse-01. ie. docker kill clickhouse-01
3. Run the main method in my fork of clickhouse-java: https://github.com/simojenki/clickhouse-java/blob/main/clickhouse-http-client/src/main/java/com/clickhouse/client/http/LoadBalancerExample.java#L52

### Expected behavior
Expected outcome is that when we get a node using nodes.apply(ClickHouseNodeSelector.of(ClickHouseProtocol.HTTP))
that node is both available, and used for the request, expected stdout from this main method would be;
- many lines like below as 8123 is a faulty node as is down, so 8123 should never be queried, 8124 is alive and healthy so should never appear in the fauly nodes list
```
check: nodes:[localhost:8124], faulty:[localhost:8123]
```
- many progress '.'
- no ERRORs

### Actual behaviour
For some reason ClickHouseNodes flips between 8123 & 8124 being faulty, even though only 8123 has been stopped, and 8124 is running the entire time.
Summary of logs of main method are;

-  For some reason 8124 is also deemed faulty sometimes; ie.
```
2023-12-19T09:17:03.310083654Z check: nodes:[localhost:8123], faulty:[localhost:8124]
```

-  Sometimes both are faulty; ie.
```
2023-12-19T09:17:03.351453583Z check: nodes:[], faulty:[localhost:8124, localhost:8123]
```

- Sometimes none are faulty, even though 8123 is down for the entire time this program is run; ie.
```
2023-12-19T09:17:03.340444470Z check: nodes:[localhost:8124, localhost:8123], faulty:[]
```

- Also sometimes we get a node using nodes.apply(...), however when the actual client is created we instead end up using the other host;
- ie in the logs it shows up like;.
```
??? asked node:http://localhost:8124/ for a node, got:http://localhost:8123/
2023-12-19T09:17:03.532582686Z ERROR trying to query:http://localhost:8124/, however client is pointing at:Agent{client=ClickHouseHttpClient{http://localhost:8123/}}
```

Interestingly, uncommenting 
https://github.com/simojenki/clickhouse-java/blob/main/clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseNode.java#L1199
and making this apply function on ClickHouseNode only ever return itself seems to resolve the issue, we get no errors, and 8123 also always faulty, no flapping about.

### Code example
- See https://github.com/simojenki/clickhouse-java/blob/main/clickhouse-http-client/src/main/java/com/clickhouse/client/http/LoadBalancerExample.java

#### Environment
* Client version: tested with 0.4.6, 0.5.0 and tip of master in fork
* Language version:
* OS:  Tested on Windows and Linux

#### ClickHouse server
* ClickHouse Server version: 23.8.2.7
* ClickHouse Server non-default settings, if any: N/A
* `CREATE TABLE` statements for tables involved: No tables created.
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary N/A

**Comment by mzitnik** [comment]
@simojenki We need to check it, but until then can you please test the usage of https://github.com/ContentSquare/chproxy

**Comment by cwurm** [comment]
@mzitnik FYI, I looked into this just before the holidays and found what I think is an issue in the `ClickHouseClient.ping` method where it's not always pinging the server it's supposed to but whatever server is available. So a faulty server will never be re-pinged and marked as healthy again. A simple one-line code change seems to fix it for me: https://github.com/ClickHouse/clickhouse-java/compare/main...cwurm:clickhouse-java:fix_ping?expand=1

Waiting to see if it will fix @simojenki's problem and if it does I can open a PR.

**Comment by simojenki** [comment]
Thank-you both for looking into this.  

@mzitnik I took a brief look at chproxy, however at this stage we would prefer not to go down that path as getting new software into our corporate environment is complicated, as such I was hoping to be able to get java client side load balancing/fail-over working, either using the ClickhouseNodes class, or rolling our own using standalone ClickhouseNode instances.

@cwurm I applied your PR to my branch and I see a different problem;

Using cluster_1S_2R from the examples;

Successful case;
- If I stop the first node 'clickhouse-01', the code will successfully fail over to the second node 'clickhouse-02'
- If I then stop the second node 'clickhouse-02' I will get errors as expected as there are no nodes running.
- I can then start up the nodes in either order and things will start working again.

Failing case;
- If I stop the second node 'clickhouse-02' first then the ClickHouseNodes.check function will not successfully detect that the node is dead, it will not be added to the faultyNodes list and as such I will see errors. 

I've managed to 'fix' the issue on my branch by removing the use of 'healthyNodeStartIndex' in ClickHouseNodes.check.  I'm not sure exactly how this field is meant to be used however it seems that maintaining an index where the healthy nodes start from assumes that the list is sorted correctly.

**Comment by cwurm** [comment]
> I've managed to 'fix' the issue on my branch by removing the use of 'healthyNodeStartIndex' in ClickHouseNodes.check. I'm not sure exactly how this field is meant to be used however it seems that maintaining an index where the healthy nodes start from assumes that the list is sorted correctly.

There seems to be a wrong condition here - the list is sorted faulty nodes first and healthy nodes second, so it should update anything past `healthyNodeStartIndex` to faulty, but it's doing the opposite: https://github.com/ClickHouse/clickhouse-java/blob/7c98c9600ad3ff9965ac24fe7a8f56fab313dbaa/clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseNodes.java#L598-L600

@simojenki I've updated my branch. Can you give it another try? https://github.com/ClickHouse/clickhouse-java/compare/main...cwurm:clickhouse-java:fix_ping?expand=1

**Comment by simojenki** [comment]
@cwurm  Yes, with your latest change I can stop clickhouse-02 and it will be correctly detected.

**Comment by cwurm** [comment]
@simojenki Great, I've opened a PR to fix this: https://github.com/ClickHouse/clickhouse-java/pull/1511
