### ISSUE TITLE
dose ck support rewriteBatchedStatements when i use ck jdbc client 

### ISSUE THREAD

**Issue by z7658329** [ClickHouse/clickhouse-java#1507]
in my case ,i  have used jdbc：
https://github.com/ClickHouse/clickhouse-java/blob/main/examples/jdbc/src/main/java/com/clickhouse/examples/jdbc/Basic.java

**here is my config:**
spring:
  datasource:
    url: jdbc:ch://xxxxxxxxx/default?rewriteBatchedStatements=true
    username:
    password:
    driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
    hikari:
      maximum-pool-size: 500
      minimum-idle: 50
      connection-timeout: 5000

**write code:**
i use jdbcTemplate:
jdbcTemplate.batchUpdate(batchInsertSql, new BatchPreparedStatementSetter()

**dose ck support rewriteBatchedStatements param when i use ck jdbc client ？**

**Comment by mzitnik** [comment]
@z7658329 Can you please attach a code snippet
