### ISSUE TITLE
ru.yandex.clickhouse and com.clickhouse conflict

### ISSUE THREAD

**Issue by BJPotter** [ClickHouse/clickhouse-java#1521]
I have two parts of code, one with ru.yandex.clickhouse-clickhouse-jdbc 0.3.2 and one with com.clickhouse-clickhouse-jdbc 0.5.0 The old version supports inserting null values, the new version must set the database table to nullable, and now it is required to merge the two parts of the code, how to solve this conflict, both parts of the code have been in production, It's inconvenient to modify the database table, is there any good solution to merge the two parts of the code now?

**Comment by mzitnik** [comment]
@BJPotter Can please provide a sample of the two sceneries so it will easier to reproduce

**Comment by BJPotter** [comment]
oh my god,It's not convenient to provide these two production projects, I just want to solve the problem that the new version of the database table must be set to null in order to insert null in java?

**Comment by dolfinus** [comment]
Have you tried option `nullAsDefault`? https://clickhouse.com/docs/en/integrations/java#configuration

**Comment by BJPotter** [comment]
Luckily, I solved this problem, thank you very much !!! i use url = jdbc:clickhouse:http://host:8123/tutorial?nullAsDefault=3 @dolfinus @mzitnik

**Comment by BJPotter** [comment]
Summary: When there is a null value conflict between the old and new versions of ru.yandex.clickhouse and com.clickhouse, we can use the url to add nullAsDefault=3 to solve the conflict
