### ISSUE TITLE
Jdbc driver can't understand data type "Nothing" and fails to execute query.

### ISSUE THREAD

**Issue by nikhilbhawsar** [ClickHouse/clickhouse-java#1546]
### Describe the bug
We have table at Clickhouse DB with columns having datatype `Nullable(Nothing)`.
We are using Spotfire desktop with latest version of CH drivers `(0.6.0)`.
While executing simple `select` query, it fails and throws error..

### Steps to reproduce
1. Create/Add column of type Nullable(Nothing)
2. Use latest version of CH driver and use it at Spotfire
3. Call "select" query for table having that column

### Expected behaviour
it should run and show results from that table.

### Code example
```java
```
### Error log
`com.spotfire.ws.im.IMException: Failed to execute query: Unsupported JDBC data type in query result: Nullable(Nothing)`

#### Environment
* Client version: clickhouse-jdbc
0.6.0
* Language version:
* OS:

#### ClickHouse server
* ClickHouse Server version:
* ClickHouse Server non-default settings, if any:
* `CREATE TABLE` statements for tables involved:
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary

**Comment by dolfinus** [comment]
This is `com.spotfire.ws.im.IMException` exception, not `com.clickhouse...` one
