### ISSUE TITLE
com.clickhouse.client.ClickHouseException#getErrorCode returns wrong code

### ISSUE THREAD

**Issue by pan3793** [ClickHouse/clickhouse-java#1547]
TL;DR - with the default configuration, when accessing ClickHouse 23.10 or above, the `com.clickhouse.client.ClickHouseException#getErrorCode` can not extract the error code correctly.

The issue can be reproduced with the latest 0.4, 0.5, 0.6 versions

The issue is detected in https://github.com/housepower/spark-clickhouse-connector/issues/286.

**Comment by mshustov** [comment]
fixed by https://github.com/ClickHouse/clickhouse-java/pull/1577
