### ISSUE TITLE
Sending client hostname(ip) to ClickHouse by default

### ISSUE THREAD

**Issue by JackyWoo** [ClickHouse/clickhouse-java#1572]
### Motivation

In production client and ClickHouse are usually not connected directly. So we can not get which client send a query in system.query_log table.

But we need it in some case for examaple log auditing.

### How to achieve?

1. For Native protocal: `client_hostname` 
2. For Http protocal: `http_referer` #1573

**Comment by chernser** [comment]
https://github.com/ClickHouse/clickhouse-java/pull/1573 merged
