### ISSUE TITLE
there is a bug when dbeaver try to connect the clickhouse

### ISSUE THREAD

**Issue by liumilan** [ClickHouse/clickhouse-java#1579]
dbeaver version is 24.0.1，and there is bug reporting when i install in in mac m1 ，how can i fix it

```
Can't create driver instance
  Error creating driver 'ClickHouse (Legacy)' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'com.clickhouse.jdbc.ClickHouseDriver'
  Error creating driver 'ClickHouse (Legacy)' instance.
Most likely required jar files are missing.
You should configure jars in driver settings.

Reason: can't load driver class 'com.clickhouse.jdbc.ClickHouseDriver'
    com.clickhouse.jdbc.ClickHouseDriver
    com.clickhouse.jdbc.ClickHouseDriver

```

**Comment by chernser** [comment]
Good day, @liumilan ! 
DBeaver using JDBC drivers for databases to connect. DBeaver Community is distributed without pre-packed drivers. It mean that user need to download needed driver. I've found this guide https://dbeaver.com/docs/dbeaver/Database-drivers/

I've checked on the 24.0.1 and the DBeaver suggests to download needed drivers. 

I've noticed that you are trying to use "Legacy" version. It may be another problem if you need to work with newer ">21.0" version of ClickHouse. 

Please let me know if it helped.
