### ISSUE TITLE
find a bug in clickhouse-jdbc 0.6.0

### ISSUE THREAD

**Issue by Young0516** [ClickHouse/clickhouse-java#1641]
bug code : com.clickhouse.jdbc.internal.ClickHouseConnectionImpl#getTableColumns line 260

when I have a following table , this table contains a cloumn named '0' 
<img width="872" alt="image" src="https://github.com/ClickHouse/clickhouse-java/assets/35856569/230221c6-90f8-41ae-bd12-603a19748243">

<img width="978" alt="image" src="https://github.com/ClickHouse/clickhouse-java/assets/35856569/d56f5524-96b1-46b8-a68b-010074976efe">

in this code, it will run the sql:  
<img width="860" alt="image" src="https://github.com/ClickHouse/clickhouse-java/assets/35856569/6d00dcf5-4517-4dd2-a36e-6d4b457625a4">

this sql will get an error:
Code: 59. DB::Exception: Illegal type Float64 of column 0 for filter. Must be UInt8 or Nullable(UInt8). (ILLEGAL_TYPE_OF_COLUMN_FOR_FILTER) (version 23.8.9.54 (official build))

when I remove 'where 0', it's ok

**Comment by chernser** [comment]
Good day, @Young0516!
This is limitation according to the documentation https://clickhouse.com/docs/en/sql-reference/statements/select/where
Actually client doesn't validate this and Code: 59 is what returned by server (repo https://github.com/ClickHouse/ClickHouse).

**Comment by Young0516** [comment]
@chernser Hi chernser thanks for your responese,  I think the rootcause is that there is a column  named '0',  I may need to report the bug to server (repo https://github.com/ClickHouse/ClickHouse).
