### ISSUE TITLE
Github releases sometimes have no description 

### ISSUE THREAD

**Issue by dolfinus** [ClickHouse/clickhouse-java#1653]
For example, 0.6.0-patch4 version currently have no description:
<details>

![Screenshot_20240526-210108_GitHub.png](https://github.com/ClickHouse/clickhouse-java/assets/4661021/6f618bac-07b1-4f3e-92f8-b2feaea86a29)
</details>

But it is present in the changelog:
<details>

![Screenshot_20240526-210123_GitHub.png](https://github.com/ClickHouse/clickhouse-java/assets/4661021/2ff9322b-0548-4f2d-b345-7f2f67140161)
</details>

Also 0.6.0-patch5 release description is different from CHANGELOD.md content:
<details>

![Screenshot_20240526-210416_GitHub.png](https://github.com/ClickHouse/clickhouse-java/assets/4661021/48b95500-3957-4cb8-81d6-4e2af663268d)
</details>

But 0.6.0-patch3 is fine:
<details>

![Screenshot_20240526-210903_GitHub.png](https://github.com/ClickHouse/clickhouse-java/assets/4661021/450897bd-1579-4cf4-a12a-456c39f25456)

![Screenshot_20240526-210420_GitHub.png](https://github.com/ClickHouse/clickhouse-java/assets/4661021/61e4368a-8529-42ff-9fdb-f4813d5ebe84)

</details>

Is everything okay with release CI workflow?

**Comment by chernser** [comment]
Good day, @dolfinus! Thank you for pointing out. 
Currently it is filled manually while release process. I've fixed most recent releases.

**Comment by dolfinus** [comment]
Thanks!
