### ISSUE TITLE
Can not get column MetaData when execute a desc query

### ISSUE THREAD

**Issue by JaynLau** [ClickHouse/clickhouse-java#1776]
### Describe the bug
When log4j2 jdbc appender insert logs into clickhouse, clickhouse use a "desc ({SQL})" statement to get column MetaData, but clickhouse-java-0.6.4 dropped `!response.getColumns().isEmpty()` in `ClickHouseStatementImpl.updateResult()`, then getMetaData() return empty!

clickhouse-java-0.6.3:
![图片](https://github.com/user-attachments/assets/5489228c-4de5-4a62-88b5-18229d6e2e2a)
clickhouse-java-0.6.4:
![图片](https://github.com/user-attachments/assets/fe143521-e01e-4394-b904-82995e744120)

log4j2 can not get the column meta data now!!!

#### Environment
* Client version: 0.6.4

**Comment by chernser** [comment]
@JaynLau thank you for reporting! 
Will fix.
