### ISSUE TITLE
[client-v2] Exception when trying to read data from an empty result GenericRecord 

### ISSUE THREAD

**Issue by unlimited-creative14** [ClickHouse/clickhouse-java#1788]
### Describe your feedback
It should not go inside the for loop because the query return empty dataset. See my example below

### Code example
```java
        Client clickhouseV2Client = new Client.Builder()
                .addEndpoint("http://localhost:8123")
                .setDefaultDatabase("default")
                .setUsername("")
                .setPassword("")
                .build();
        CompletableFuture<Records> query = clickhouseV2Client.queryRecords("SELECT 1 LIMIT 0");
        for (GenericRecord record : query.get()) {
            System.out.println("record.c1 = " + record.getInteger(1));
        }
```

There are stack traces:
java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because "this.currentRecord" is null
	at com.clickhouse.client.api.data_formats.internal.AbstractBinaryFormatReader.readValue(AbstractBinaryFormatReader.java:104) ~[client-v2-0.6.4.jar:client-v2 0.6.4 (revision: fc8d92e)]
	at com.clickhouse.client.api.data_formats.internal.AbstractBinaryFormatReader.getString(AbstractBinaryFormatReader.java:169) ~[client-v2-0.6.4.jar:client-v2 0.6.4 (revision: fc8d92e)]
	at com.clickhouse.client.api.data_formats.internal.BinaryReaderBackedRecord.getString(BinaryReaderBackedRecord.java:32) ~[client-v2-0.6.4.jar:client-v2 0.6.4 (revision: fc8d92e)]

**Comment by mzitnik** [comment]
@unlimited-creative14 Thanks for the feedback

**Comment by tiagociprianopires** [comment]
This issue occurs on all query() method, including:
    public CompletableFuture<QueryResponse> query(String sqlQuery, Map<String, Object> queryParams, QuerySettings settings)

This is still happening in 0.6.5

As a workaround for those who found this issue before it's fixed, check the number of records prior to iterate:

```java
   CompletableFuture<Records> query = clickhouseV2Client.queryRecords("SELECT 1 LIMIT 0");
    Records genericRecords = query.get();
    if (genericRecords.getResultRows() > 0) {
      for (GenericRecord record : genericRecords) {
        System.out.println("record.c1 = " + record.getInteger(1));
      }
    }

```

**Comment by chernser** [comment]
Thank you, @tiagociprianopires !
