### ISSUE TITLE
[client-v2] Handling errors from a server

### ISSUE THREAD

**Issue by chernser** [ClickHouse/clickhouse-java#1821]
When compression is on (default case) and error happens - it is read from a raw stream, but should be wrapped with LZ4 Input Stream. 

### Steps to reproduce
1. send query `select asd123` 
2. observe error with non-ascii symbols 

### Expected behavior

Error message should be a human readable string 

### Code example
```java
```
#### Environment
* Client version:
* Language version:
* OS:

#### ClickHouse server
* ClickHouse Server version:
* ClickHouse Server non-default settings, if any:
* `CREATE TABLE` statements for tables involved:
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary

**Comment by Am-phi** [comment]
@chernser  
Didn't you already fixed this issue in #1830 ? Your description seems reproducible before this PR, and not after it.

**Comment by chernser** [comment]
Good day, @Am-phi! 
yes, #1830 fixes most of the problems and I left issue open to test more and fix may be edge cases. 
There is a tricky case when error is within data stream in the format of the data stream. It is fixed too, but I would spend sometime for additional tests.
