### ISSUE TITLE
[jdbc] JDBC has dependency on SNAPSHOT version of the clickhouse-http-client

### ISSUE THREAD

**Issue by livk-cloud** [ClickHouse/clickhouse-java#1853]
when I use com.clickhouse:clickhouse-jdbc:0.7.0, I find something bad

this is shown in the figure below

![4831d950d82d4cd6e0737ecbe65173d5](https://github.com/user-attachments/assets/c3939020-6084-411c-9011-5eb77a3562e2)

I don't understand why 0.7.0-SNAPSHOT is happening, not 0.7.0

**Comment by chernser** [comment]
Hi, @livk-cloud ! 
Thank you for reporting the issue. It is because a duplicate dependency was added with hardcoded version. 
Will fix in the next release.
