### ISSUE TITLE
Can't use Array of Tuple in PreparedStatement

### ISSUE THREAD

**Issue by joceron** [ClickHouse/clickhouse-java#1862]
I'm trying to use an Array of Tuple in a PreparedStatement, but somehow while serializing, it seems the Tuple gets combined into a single value. I don't know if it's due to my misunderstanding of how to use the driver, or an actual bug. If it's the first case, I apologize.

I created an example table with this:
```sql
CREATE TABLE tmp (my_column Array(Tuple(String, String))) PRIMARY KEY my_column;
```

And this is my testing code:
```scala
val conn = DriverManager.getConnection(???, ???, ???)
val pstmt: PreparedStatement = conn.prepareStatement("insert into tmp (my_column) values (?)")
val arr  = conn.createArrayOf("Tuple(String, String)", List(("first", "second")).toArray[Object])
pstmt.setArray(1, arr)
pstmt.executeUpdate()
```

When executing that, it goes to `BinaryDataProcessor.ArraySerializer.serialize`, and then I see that at that point so far the serializing goes well:
![Screenshot 2024-10-10 at 15 08 58](https://github.com/user-attachments/assets/9066467b-3fea-49db-8315-bbd92e26ff63)

But then when going into `ClickHouseRowBinaryProcessor.TupleSerializer.serialize` later during the execution, it seems that it has combined the whole tuple into a single value:
![Screenshot 2024-10-10 at 15 10 07](https://github.com/user-attachments/assets/8dc83170-3df6-4ddb-a09a-dac73bdd567a)

That throws an`IndexOutOfBoundsException`, because (I'm copy&pasting code from `ClickHouseRowBinaryProcessor`):
```java
public void serialize(ClickHouseValue value, ClickHouseOutputStream output) throws IOException {
    List<Object> tupleValues = value.asTuple();
    int i = 0;

    for(int len = this.serializers.length; i < len; ++i) {
        this.serializers[i].serialize(this.values[i].update(tupleValues.get(i)), output);
    }

}
```
There, `tupleValues`, I suppose it's meant to have two values: each of the values of the Tuple. But since it was combined into one (see my second screenshot), in the `for` loop it throws an exception when trying to do `tupleValues.get(1)`.

Amd I misunderstanding something?

**Comment by 7hong** [comment]
You can use `Array` instead of `Tuple`, like this:


```scala
connection.createArrayOf(
        "Tuple(String, String)",
        List(Array("first", "second"), Array("aa", "bb")).toArray[Object]
      )
```
or

```scala
connection.createArrayOf(
        "Tuple(String, String)",
        Array(Array("first", "second"), Array("aa", "bb"))
      )
```

@joceron

**Comment by joceron** [comment]
Thank you very much @7hong ! That worked
