### ISSUE TITLE
0.7.0 Release using SNAPSHOT dependency

### ISSUE THREAD

**Issue by harmonic-ben** [ClickHouse/clickhouse-java#1888]
### Steps to reproduce
1. Depend on 0.7.0 release of clickhouse-jdbc and get a transitive dependency on `clickhouse-http-client:0.7.0-SNAPSHOT`

### Expected behaviour
1. For there to be a transitive dependency on `clickhouse-http-client:0.7.0`

You can see this here : https://mvnrepository.com/artifact/com.clickhouse/clickhouse-jdbc/0.7.0

**Comment by Am-phi** [comment]
related to #1853
