### ISSUE TITLE
[jdbc] The ClickHouseHttpConnection overrides `result_overflow_mode`.  

### ISSUE THREAD

**Issue by chernser** [ClickHouse/clickhouse-java#1932]
### Description 
There is a setting `result_overflow_mode` that controls what to do when result limit exceeded ([doc](https://clickhouse.com/docs/en/operations/settings/settings#result_overflow_mode)). Current JDBC implementation doesn't let an user to override this settings. It is especially needed when `use_query_cache` is set. In such cases `result_overflow_mode` would be `throw`. 

See also https://github.com/ClickHouse/ClickHouse/pull/69549 
Query Cache https://clickhouse.com/docs/en/operations/query-cache#configuration-settings-and-usage

**Comment by saud-cloud** [comment]
I am facing same issue with overflow_mode
