### ISSUE TITLE
Ability to KILL query via JDBC in clustered environment

### ISSUE THREAD

**Issue by devozerov** [ClickHouse/clickhouse-java#1981]
When JDBC `Statement.cancel` method is invoked, a `KILL QUERY` query is executed. If ClickHouse is started in a clustered environment, sometimes this may fail to kill the query on all nodes because the proper command is `KILL QUERY ON CLUSTER`. Currently, there is no way to do this. 

The proposal is to add a client configuration property with a cluster name. When specified, the JDBC driver should call `KILL QUERY ON CLUSTER` instead of `KILL QUERY`.

If this is difficult to achieve, at the very least lets expose the `query_id` from the Statement (https://github.com/ClickHouse/clickhouse-java/issues/392). In this case, the user will be able to invoke the command manually:
```
ClickHouseStatement chStatement = statement.unwrap(ClickHouseStatement.class);
Optional<String> queryId = chStatement.getQueryId();
if (queryId.isPresent()) {
    try (Statement killStatement = connection.createStatement()) {
        killStatement.executeUpdate("KILL QUERY ON CLUSTER ... WHERE query_id = " + queryId.get());
    }
}
```

**Comment by chernser** [comment]
Good day, @devozerov ! 
Thank you for reporting - will look into it.

**Comment by mshustov** [comment]
@Paultagoras closed by https://github.com/ClickHouse/clickhouse-java/pull/1984?
