### ISSUE TITLE
Fix version detection

### ISSUE THREAD

**Issue by Paultagoras** [ClickHouse/clickhouse-java#2007]
Problems to solve:
- Reports a wrong client version or update didn’t happen.
- Reports never released kafka connector version (`v1.2.10`)
- The existing tests haven't caught the problem

Currently we're defaulting to 0.6.3:

public static final String LATEST_KNOWN_VERSION = "0.6.3";

We need to find a more reliable way to determine the version...

**Comment by mshustov** [comment]
or don't guess and set a well-known indicator like `unknown`, which would help us to detect problems earlier and fix them

**Comment by chernser** [comment]
@mshustov we need to know at least aprox. version - so I've added `~` to version constant. 
Event if we missed updating it - we will get something `~0.7.2`. 
Please let me know if this will work. 

Thanks!
