### ISSUE TITLE
ClickHouseStatement not load file into table ( file name too long)

### ISSUE THREAD

**Issue by vladsaraykin** [ClickHouse/clickhouse-java#401]
version driver clickhouse-jdbc:0.2
I have csv file with columns which have cyrillic (7 columns  which each one have near 40 cyrillic symbols).
Name table is cyillic too.
Request:
```
                try (InputStream inputStream = Files.newInputStream(file);
                     ClickHouseStatement statement = clickHouseConnection.createStatement()) {
                    statement.write()
                            .table(tableName))
                            .option("format_csv_delimiter", ";")
                            .data(inputStream, ClickHouseFormat.CSV)
                            .send();
                }
```
Response:

> ru.yandex.clickhouse.except.ClickHouseException: ClickHouse exception, code: 76, host: localhost, port: 3307; Code: 76, e.displayText() = DB::ErrnoException: Cannot open file /var/lib/clickhouse/data/goSNynThCyuHpAZGJwCC/%D0%92%D1%8B%D0%B3%D1%80%D1%83%D0%B7%D0%BA%D0%B0%20%D0%B4%D0%BB%D1%8F%20%D0%B4%D0%B0%D1%88%D0%B1%D0%BE%D1%80%D0%B4%D0%B8%D0%BD%D0%B3%D0%B0%2Etxt%281%29/tmp_insert_all_1_1_0/%D0%92%D1%8B%D0%B3%D1%80%D1%83%D0%B7%D0%BA%D0%B0%20%D0%B4%D0%BB%D1%8F%20%D0%B4%D0%B0%D1%88%D0%B1%D0%BE%D1%80%D0%B4%D0%B8%D0%BD%D0%B3%D0%B0%2Etxt%2E%D0%A0%D0%B5%D0%B3%D0%B8%D0%BE%D0%BD%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9%20%D1%84%D0%B8%D0%BB%D0%B8%D0%B0%D0%BB.bin, errno: 36, strerror: File name too long (version 19.14.6.12 (official build))

**Comment by den-crane** [comment]
Linux has a maximum filename length of 255 characters for most filesystems (including EXT4), and a maximum path of 4096 characters

Not JDBC issue. CH does not support so long column names.
