### ISSUE TITLE
Transaction support

### ISSUE THREAD

**Issue by zhicwu** [ClickHouse/clickhouse-java#975]
**Server**
- Transaction ID: `Tuple(snapshot_version UInt64, local_txid_counter UInt64, host_id UUID)`
- functions: `transactionID()`, `transactionLatestSnapshot()`, `transactionOldestSnapshot()`
- settings: `throw_on_unsupported_query_inside_transaction`, `wait_changes_become_visible_after_commit_mode`, `implicit_transaction`
- statements: `begin transaction`, `commit`, `rollback`, `set transaction snapshot <snapshot id>`, `kill transaction where tid=<transaction id>`

**Java Client**
- [x] new client option `transaction_timeout`, defaults to `session_timeout`
- [x] add `ClickHouseTransaction` with methods for begin/commit/rollback transaction and snapshot
- [x] add `ClickHouseRequestManager` for generating query id and session id as well as transaction creation
- [x] enhance `ClickHouseRequest` by adding methods getTransaction and setTransaction - multiple requests can take part in one transaction
- [x] throw `ClickHouseTransactionException` for `Code: 649. DB::Exception: Cannot execute query because current transaction failed. Expecting ROLLBACK statement. (INVALID_TRANSACTION)` - server will rollback automatically but still needs client to explicitly to acknowledge that by issue `rollback`(using `connection.rollback()`)
- [x] always create new session when `begin transaction` and enforce `session_check` until transaction completed
- [x] consider transaction in `retry` and `failover`(avoid node switching)

**JDBC Driver**
- [x] new JDBC option `transactionSupport` (defaults to `false`)
- [x] use `implicit_transaction` in auto commit mode, fallback to TCL when it's not supported
- [x] replace `FakeTransaction` when transaction support is enabled
- [x] change default transaction isolation level to repeatable-read([why?](https://github.com/ClickHouse/ClickHouse/issues/39435#issuecomment-1191386573))
- [x] parse TCL to maintain transaction consistency between server and client in 0.3.3?
- [x] update SIT base classes in 0.3.3 to use docker-compose instead of standalone container and then enable tests for HA and TX in CI

**Comment by zhicwu** [comment]
Performance penalty for transaction support is acceptable(on client side):

![image](https://user-images.githubusercontent.com/4270380/181141831-81545d20-2640-4563-987f-61f0b101fe8c.png)

**Comment by hantaoliulinux** [comment]
Hello, can you provide an example of transactional data insertion using PreparedStatement about JDBC Driver?

**Comment by zhicwu** [comment]
> Hello, can you provide an example of transactional data insertion using PreparedStatement about JDBC Driver?

Hi @hantaoliulinux, did you run into any issue using above examples? The usage is same for Statement and PreparedStatement. FYI, transaction won't start in 0.4.0 and 0.4.1, please use v0.3.2-patch11(or wait for 0.4.2) for transaction support.
