### ISSUE TITLE
Cannot build the project

### ISSUE THREAD

**Issue by sumitsethia94** [ClickHouse/clickhouse-java#993]
Hi, I get the module not found error when doing "mvn clean install" or "mvn clean verify" or "mvn -Drelease clean install"
I am using jdk 17 and have both 11 and 17 specified in mvn toolchain.
Can any one please help? Thanks!

Output of "mvn -Drelease clean install"

<img width="1063" alt="image" src="https://user-images.githubusercontent.com/44174724/178463074-6e9e71aa-f026-4e11-a8b7-62b3347c7a98.png">

Output of mvn toolchain.xml

<img width="721" alt="image" src="https://user-images.githubusercontent.com/44174724/178463146-671b6975-6d31-4042-a6ce-7dfce28a5896.png">

**Comment by zhicwu** [comment]
Hi @sumitsethia94, the configuration looks good to me. Could you try below against `develop` branch?

```bash
cd clickhouse-client
mvn -Drelease clean install
cd ../clickhouse-cli-client
mvn -Drelease clena install
...
```
